### ISSUE TITLE
Why do not use recover when use goroutine, it is dangerous.

### ISSUE THREAD

**Issue by Fatfish90** [storj/storj#1053]
Such like:  pkg/kademlia/peer_discovery.go#L61
Do not use recover to catch goroutine exception, maybe could follow what recommended in <<Effective Go>>:   https://golang.org/doc/effective_go.html#recover

**Comment by egonelbre** [comment]
The problem is that after a panic there isn't a really nice to know what exactly went wrong and continuing might do more damage than stopping and restarting the process. We also need to assume that the servers will crash or stop whether we like it or not (e.g. power outage). In essence the software should handle hard reset, which also covers panic.

You can read about these ideas in:
1. http://www.hpl.hp.com/techreports/tandem/TR-85.7.pdf
2. http://erlang.org/download/armstrong_thesis_2003.pdf

However, in some-cases, yeah, it might make sense to handle panics more gracefully and catch more context or make backups of important things.
