### ISSUE TITLE
Executables not found

### ISSUE THREAD

**Issue by Luca8991** [storj/storj#1284]
When I try to execute 
```bash
./storj-sim network setup
```
it comes out with
```bash
Error: some executables cannot be found: [bootstrap gateway satellite storagenode]
```
as I'm the folder with all executables needed (`~/go/bin`)

**Comment by stefanbenten** [comment]
@Luca8991 Your PATH is missing the folder then. We are relying on the PATH containing this folder with the binaries, to be able to call it without specificing the path all the time.

Adding the following should solve that:
`export PATH=%HOME%/go/bin:$PATH`

Thank you for testing the V3 Network!

**Comment by Luca8991** [comment]
> @Luca8991 Your PATH is missing the folder then. We are relying on the PATH containing this folder with the binaries, to be able to call it without specificing the path all the time.
> 
> Adding the following should solve that:
> `export PATH=%HOME%/go/bin:$PATH`
> 
> Thank you for testing the V3 Network!

After doing `export`, it comes out with the same error again.

**Comment by stefanbenten** [comment]
Can you post the result of `echo $PATH`?

**Comment by Luca8991** [comment]
@stefanbenten sorry! I didn't change your suggested path to the path of my `go/bin` folder... Now it works!

**Comment by stefanbenten** [comment]
Perfect, happy testing! @Luca8991

**Comment by InKastraRedBrother** [comment]
![Uploading Снимок экрана от 2019-12-22 22-37-17.png…]() There mine, i dunno whats wrong. Didnt work on Win10 , didnt work on linux with the same error

**Comment by ifraixedes** [comment]
Currently, for running `storj-sim` you must have the `redis-server` executable in any directory referenced by your `PATH` variable or setup a redis server and configure the connection URL to it.

See those instructions in https://github.com/storj/storj/wiki/Test-network#using-redis

By the way, `PATH` environment variable contains paths to directories not to a single binary so you don't have to add one by one the path to all the binaries.

**Comment by bluescalesolutions** [comment]
So on Linux (Manjaro) the section in this documenthttps://github.com/storj/storj/wiki/Test-network,  Installation and configuration where it says:  

By default, this is ~/go/bin. If this location is not in your $PATH add it by running `export PATH="~/go/bin:$PATH"`.


what you actually want is 


By default, this is ~/go/bin. If this location is not in your $PATH add it by running `export PATH="$HOME/go/bin:$PATH"`.  The substitution from tilde to $HOME is because tilde is not resolved reliably.  Also you want to add this to your ~/.bashrc so this is always in your path.


after that minor adjustment everything works fine.
