### ISSUE TITLE
Thousands of empty folders - cleanup needed?

### ISSUE THREAD

**Issue by mgittelman** [storj/storj#1502]
I noticed that for 7.7GB stored, I currently have over 98000 items, most of which seem to be empty folders.  Are these needed for a reason?  Are they created when files are stored and then left behind when files are deleted?

As the amount of storage scales up I'm worried about potentially millions of empty folders.  Can something be done about this?

**Comment by egonelbre** [comment]
Currently we are doing a lot of testing that looks like upload, download and delete. Realistically people won't use it that way, but end up storing things for long time.

Yes, we are not deleting the folders at the moment, because while checking whether folder is empty and deleting, something else could start writing to that specific folder causing problems. I added an issue to do that during restart however.

But, with next storage node data layout the number of folders will be capped at `number of satellites * 1024`. So there's less problems with that approach.

**Comment by stefanbenten** [comment]
This issue has been addressed and rolled out to the storagenodes!
