### ISSUE TITLE
Storage node hogging up all my bandwidth

### ISSUE THREAD

**Issue by meetyg** [storj/storj#1864]
Hi. 
I'm running the latest Storage node docker (using watchtower for updates) on an ARM device running Linux. 

While its working pretty well, at times it hogs all my internet bandwidth, making other devices on my network very slow.

Is there a way to limit the percent of bandwidth that the node is allowed to use at any given time?

I'm not talking about bandwidth cap, I allready have that configured in the docker command. 

I'm talking about bandwidth percent (such as mentioned in the payment calculator).

It would be nice if there were such a configuration at the container level, since my device runs other containers too, and I want to limit only the Storj container. 
As far as I know Docker doesn't have this feature built-in, but I think it should be a feature of the storage node software itself.

BTW, I think Storj is pretty cool and like the idea of decentralized storage. I'm happy to take part of the network :-)

**Comment by aligeti** [comment]
@meetyg currently storage nodes operates off of two parameters. The size of the space allocated and bandwidth to use. This is something we can look into it. Thanks for bringing this up.

**Comment by iglesiasbrandon** [comment]
Hello @meetyg, 

We this feature on our product road map. We are planning on incorporating [LEDBAT](https://en.wikipedia.org/wiki/LEDBAT) into the Storj Node software so that nodes can transfer data without clogging the network. 

If you want to stay up to date with upcoming features please check out our [roadmap](https://storjlabs.aha.io/published/01ee405b4bd8d14208c5256d70d73a38?page=1)
or our [development updateds](https://storj.io/blog/authors/brandon-iglesias/) every 2 weeks!

**Comment by meetyg** [comment]
That sounds cool Brandon !
It seems that LEDBAT is a better solution than what I was looking at, mainly traffic shaping using Linux's ´tc´ command. 
I'll have a look at the roadmap, looking forward to this feature. I'm allready a fan of your excellent blog +1.
Should I keep this issue open so that I can comment on it when you imolement the feture or should I close it for now ?

**Comment by BlackDuck888** [comment]
Why STORJ does not tag data transfers on background QOS level? 

- You will not need an extra lib QOS is per default available
- Near all consumer router handle QOS because it is needed for VoIP
- If Network messages get higher prioritized and data transfer put on the background. Storj could be very responsive and is able to use full bandwidth if need when is free from other use. 

Storj use case is planned to share free resources, to put this traffic in the background is the logical consequence, because free can only be all unneeded.

**Comment by LHozzan** [comment]
Hello.
Spot this problem too. From my point of view it seems, like storagenode open connections in some loop and hang on router limit. I mean this:
![Snímka obrazovky z 2019-06-20 21-08-27](https://user-images.githubusercontent.com/24796361/59875287-a98ab100-93a0-11e9-91b6-60bd9d559873.png)

In first moment i rise this limit from default 1024 to 2048, but spot this problem again.
Default I use ~700 connections, so i suspect storagenode, or watchtower, or docker as is.

Restarting docker container with storagenode not help me, stop watchtower too, only restart whole computer.

If you need any aditional information, please ask.

**Comment by iglesiasbrandon** [comment]
@meetyg You can use `storage2.max-concurrent-requests` to configure this. We are going to close this issue for now; please let us know if it should be reopened.
