### ISSUE TITLE
V3 Dashboard reports wrong disk usage

### ISSUE THREAD

**Issue by chan0d** [storj/storj#1984]
This is disk used 78GB and node reports only 27.3GB. I have already tried to restart node na remove it and recreate it.

78G     /sj-node/data/

Storage Node Dashboard ( Node Version: v0.11.1 )

======================

ID           ------
Last Contact 2s ago
Uptime       4h5m12s

                   Available         Used      Egress     Ingress
     Bandwidth       19.9 TB     110.6 GB     35.8 GB     74.8 GB (since May 1)
          Disk        6.0 TB      27.3 GB

Bootstrap bootstrap.storj.io:8888
Internal  127.0.0.1:7778
External  sj-node.ddns.net:28967

Neighborhood Size 137

**Comment by sndrr** [comment]
I have the same. In the dashboard:
```
                   Available         Used       Egress      Ingress
     Bandwidth       79.6 TB     356.7 GB     120.2 GB     236.5 GB (since May 1)
          Disk        4.9 TB     110.7 GB
```
And on the disk:
```
# du -h --max-depth=1 storage
4.0K    storage/trash
167G    storage/blob
16K     storage/tmp
167G    storage
```

Is disk usage only calculated per month?

**Comment by ifraixedes** [comment]
Your storage node may have missed some delete operations; we are working on the garbage collection feature to allow storage nodes which  miss some deletions can realize a big part of them.

**Comment by krilson** [comment]
I have the same or even worse. The / partition is 100% full and now the node is crashing since the whole os is unstable. Disk size is 916GB, in the storj config 850GB is assigned. But it somehow used up all the space on the disk.

`Filesystem                  Size  Used Avail Use% Mounted on
udev                        1.8G     0  1.8G   0% /dev
tmpfs                       355M 1016K  354M   1% /run
/dev/mapper/vg-root  916G  915G     0 100% /
tmpfs                       1.8G     0  1.8G   0% /dev/shm
tmpfs                       5.0M     0  5.0M   0% /run/lock
tmpfs                       1.8G     0  1.8G   0% /sys/fs/cgroup
/dev/sda1                   472M  142M  306M  32% /boot
tmpfs                       355M     0  355M   0% /run/user/1000
`
`Storage Node Dashboard ( Node Version: v0.12.2 )

======================


                   Available         Used      Egress      Ingress
     Bandwidth       49.7 TB     339.4 GB     84.9 GB     254.5 GB (since Jun 1)
          Disk       28.7 GB       0.8 TB
`
How to solve this?

**Comment by 2mf** [comment]
I got this one, even negative
```
Storage Node Dashboard ( Node Version: v0.12.2 )

======================

                          Available           Used        Egress        Ingress
     Bandwidth       24.8 TB     232.1 GB     70.9 GB     161.1 GB (since Jun 1)
              Disk      -15.9 MB         0.8 TB

```

**Comment by and-then** [comment]
I am getting a negative too

Docker perams are BANDWIDTH="40TB" STORAGE="1TB"

```
Storage Node Dashboard ( Node Version: v0.13.0 )

                   Available         Used       Egress      Ingress
     Bandwidth       39.6 TB     403.1 GB     104.3 GB     298.8 GB (since Jun 1)
          Disk      -14.2 MB       1.0 TB
```
On the disk

```
#du -h --max-depth=1 /storj
1016G   /storj/storage
1016G   /storj

```

is there a force verify/audit?

**Comment by ifraixedes** [comment]
> is there a force verify/audit?

No there isn't.

For the rest of you, we are still looking for why that happens, thanks for your patience. If you have an important problem, please contact through our rocket chat support channel.

**Comment by LHozzan** [comment]
Hello.

Similar problem here. I have set different parameters, when I starting storagenode, but over time `Available Bandwidth` and `Available Disk` is lovering. Of course, `Used Disk` is reported wrong too.

```
Storage Node Dashboard ( Node Version: v0.13.0 )

                   Available         Used      Egress      Ingress
     Bandwidth       10.8 TB     233.8 GB     88.7 GB     145.1 GB (since Jun 1)
          Disk        2.8 TB     155.1 GB
```

Started with parameters:
```
docker run -d --restart unless-stopped -p 28967:28967 \
    -e WALLET="0xXXX" \
    -e EMAIL="XXX" \
    -e ADDRESS="XXX:28967" \
    -e BANDWIDTH="11TB" \
    -e STORAGE="3TB" \
    -v "/root/.local/share/storj/identity/storagenode":/app/identity \
    -v "/home/StorjStore":/app/config \
    --name storagenode storjlabs/storagenode:alpha
```

Disk status:
```
root@scrap:/home/storj# du -h --max-depth=1 /home/StorjStore
146G	/home/StorjStore/storage
16K	/home/StorjStore/lost+found
146G	/home/StorjStore
```

Using LVM too. As a PVs using MDs with Raid1 (yes, assembled with many small disks, but in redundancy).

If you need any aditional information, please ask.

**Comment by ifraixedes** [comment]
We use power of 1000 for calculating the [amount of used disk](https://github.com/storj/storj/blob/76b54458e950264a4e74afc461bcfec18b0c1fe9/cmd/storagenode/dashboard.go#L133) while the `du` execution that you did reports the size in power of 1024.

If you make the conversion you get that `144.44GiB` is used which is roughly to `146G`; the difference between those probably is due some garbage that your node has collected and currently we don't have the garbage collection in place, we are working on that feature.

**Comment by rbuehlma** [comment]
For me, the dashboard reports -4.5MB available and 600 GB used (the configured maximum).
"du -s --si" reports 957G (the --si argument uses 1000 instead of 1024 for the calculation)
It seems that ~37% of my data is garbage.

**Comment by ifraixedes** [comment]
@rbuehlma is a lot but could be, for that specific case, please contact with our support through rocket chat.

**Comment by xyphos10** [comment]
Hello, 

I also have experience this issue. In my case the OS reports that used space is 156G but the dashboard only shows  3.4G used


Storage Node Dashboard ( Node Version: v0.14.3 )

Last Contact 4s ago
Uptime       51h6m10s

                   Available           Used         Egress     Ingress
                   Bandwidth       15.0 TB     5.6 GB     94.4 MB      5.5 GB (since Jun 1)
                   Disk                 50.0 TB     3.4 GB


Results of du -s --si

![image](https://user-images.githubusercontent.com/31674648/60301756-69bb5080-98ef-11e9-8239-e7a3062d4366.png)

**Comment by ifraixedes** [comment]
We have taken a look to some nodes that experimented this issue. We concluded that since the release of this [fix](https://github.com/storj/storj/commit/23e081f0c710bef913c67878c3e6bd3f260f287d#diff-c8abc956f27b79755a16b8da2c392cbb) which was in the version `v0.14` the bug was fixed.

However you can still see garbage in your disk because the release fixed the issue of not leaving garbage in disk but it didn't delete the previous garbage; please wait until the next network wipe to delete them and from that on you shouldn't get garbage in your disk which isn't tracked.

If after that, you are still experimenting the problem, please open a new issue.
Thanks for you patience.

**Comment by RobQuistNL** [comment]
I'm not sure, but I don't think this actually fixes the issue.

What I think is happening: I see a LOT of tiny files that are around 1kb in size on my disk. (a LOT). The problem on the disk is blocks. A 1kb file in size will take up 4096 bytes on the disk (the size of one block). 

My current node uses 2.8TB on disk, and the actual reported size on the frontend node is 573 GB.

Could this be what is actually happening?
