### ISSUE TITLE
Kademlia issue

### ISSUE THREAD

**Issue by AlexandrTyshchenko** [storj/storj#2221]
I have two ISP, one main (main.example.com) and another backup (backup.example.com). Today my main ISP is go down for 10min. and I switched to backup ISP with the following steps:

1. `docker stop storagenode`
2. `docker rm storagenode`
3. change  `-e ADDRESS="main.example.com:28967"` to the `-e ADDRESS="backup.example.com:28967"`
4. `docker start.....` with all my parameters.

After few seconds i got a lot errors in logs
`docker logs -t storagenode --tail 100 -f`

`
2019-06-16T18:42:22.356906702Z 2019-06-16T18:42:22.356Z ERROR   untrusted: unable to get signee: trust:: node not found
2019-06-16T18:42:22.356907932Z  storj.io/storj/storagenode/piecestore.(*Endpoint).VerifyOrderLimitSignature:141
2019-06-16T18:42:22.356908262Z  storj.io/storj/storagenode/piecestore.(*Endpoint).VerifyOrderLimit:70
2019-06-16T18:42:22.356908512Z  storj.io/storj/storagenode/piecestore.(*Endpoint).Upload:157
2019-06-16T18:42:22.356908751Z  storj.io/storj/pkg/pb._Piecestore_Upload_Handler:602
2019-06-16T18:42:22.356908998Z  storj.io/storj/pkg/server.logOnErrorStreamInterceptor:23
2019-06-16T18:42:22.356909208Z  google.golang.org/grpc.(*Server).processStreamingRPC:1209
2019-06-16T18:42:22.356909423Z  google.golang.org/grpc.(*Server).handleStream:1282
2019-06-16T18:42:22.356910340Z  google.golang.org/grpc.(*Server).serveStreams.func1.1:717
`

After 10 min. main ISP is UP and I switched back to the main ISP and all errors is gone.
I thinks the same errors should be if anyone use dynamic IP.

I think kademlia should handle IP changes, please look into this issue.

**Comment by heunland** [comment]
For SNOs with dynamic IP, we recommend using a DDNS to address this issue, as described in the storagenode installation instructions.

**Comment by AlexandrTyshchenko** [comment]
I not using dynamic ip's. my ip is static.

**Comment by AlexandrTyshchenko** [comment]
and my issue not ralated to dynamic ip.

**Comment by heunland** [comment]
I was responding to your statement "I thinks the same errors should be if anyone use dynamic IP."

**Comment by AlexandrTyshchenko** [comment]
Yes, but why you close this issue?

**Comment by heunland** [comment]
Sorry from your intitial comment it was not clear you were on static IP

**Comment by jtolds** [comment]
the error messages you posted are from an outgoing connection codepath, not incoming. the configuration changes you made should have worked just fine for incoming kademlia connections, but it appears your node couldn't connect out. did you configure your route table to funnel outgoing connections out of your backup isp? it appears the node thought it had no internet access

**Comment by jtolds** [comment]
@heunland static ip is actually preferred to dynamic ip. most people have dynamic ip and have no choice about it, hence why we recommend dynamic dns providers for those people

**Comment by AlexandrTyshchenko** [comment]
> did you configure your operating system's route table to funnel outgoing connections out of your backup isp?

Yes, i make sure with `mtr google.com` and see path thru backup ISP.

Also today I reproduced it without configuration changes, here is detailed repoduce steps:

1. `docker stop storagenode`
2. do not change anything in storagenode configuration (-e ADDRESS="main.example.com:28967")
3. change IP for DNS name `main.example.com` (zone TTL is 300s) from main ISP to backup
4. wait 10min. and make sure that DNS is distributed `nslookup main.example.com 8.8.8.8`
5. switch to backup ISP
6. `docker start..... `with all my parameters.
7. check logs `docker logs -t storagenode --tail 100 -f`
8. see a lot of `ERROR untrusted: unable to get signee` about 2-3 min.
9. errors is stoped
10. see silence about 30-40sec.
11. see a lot of `Canceled desc = context canceled` about 5-7min.
12. storagenode starting work normaly

**Comment by AlexandrTyshchenko** [comment]
> Sorry from your intitial comment it was not clear you were on static IP

I apologize, it my fail, I not specified that all my ISP's have static IP

**Comment by JL421** [comment]
I have seen the `ERROR untrusted: unable to get signee: trust:: node not found` message on initial startup when the info.db file is either locked, or not mapped by docker yet. It shouldn't take a minute to map that file, but depending on your OS and how the node was stopped, it is possible that the file is still locked. Once your node can see the database file that error would go away.

The context canceled errors would then show up while your node verifying the database, which can take a few minutes depending on your disk speed. While that process is happening your node is running and listening to requests, but not actually doing anything with them. Once all the verification is complete, it starts processing the backlog of requests it had, and all of them should have been completed by other nodes while yours was busy so you get a flood of context canceled's.

Finally you start normal operating mode. None of this should have any bearing on your IP changing as your failover to your backup ISP. I would just expect your node to stop receiving any requests until the old DNS record expires and clients start grabbing the new address. Unless when your primary fails you forcibly kill the node which would explain this behavior, that shouldn't be necessary though.

On a related note, there should be a satellite response built in while the node is starting up and in its verification process. I've seen 3-5 audit requests for the same piece come in while my node was booting that caused the satellite to stop sending me data for about an hour after my node was finally available. As more data is stored on a node this process would take longer and possible cause a node to be disqualified for failing audits when there isn't actually any data loss and the node would otherwise be healthy. Maybe just a backoff response where the satellite will wait 5-10 minutes before directing any request towards the node.

**Comment by AlexandrTyshchenko** [comment]
@JL421 Thanks a lot for you clear reply!

I can confirm, that issue not related to IPS switching, I see the same errors during initial startup.
I think you are right and this issue related to info.db and her size at this moment (3.4GB for me).

**Comment by ifraixedes** [comment]
@JL421 I've registered a ticket in our internal issue tracker to inspect that problem

@AlexandrTyshchenko is it OK to you to close this issue?

**Comment by AlexandrTyshchenko** [comment]
@ifraixedes Thanks! 
Yep, let's close this issue.

**Comment by ifraixedes** [comment]
Thank you, both, for your contributions!
