### ISSUE TITLE
Error logs do not properly render `\n \t`

### ISSUE THREAD

**Issue by utdrmac** [storj/storj#3026]
See screenshot below. You can clearly see the `\n\t` within the logs. These should be properly rendered/evaluated to show an easier to read log output.

![Screen Shot 2019-09-12 at 9 37 49 AM](https://user-images.githubusercontent.com/4413670/64793678-05e51300-d541-11e9-813e-d7048cef28e5.png)

**Comment by ifraixedes** [comment]
> So, how do you correctly view docker/storj error logs then?

I personally redirect them to a file, because I don't want to lose the logs when the container gets removed on each automatic update.

[Ax](https://github.com/egnyte/ax) reads logs from docker, however, I haven't tried so I'm not sure if that can help while a feature like @thepaul suggested is planned, implemented and ultimately merged.

**Comment by jtolio** [comment]
We just merged a new change that will be in one of our upcoming releases! https://github.com/storj/private/commit/eb9021c04f9600f9785dd74fa4e266b8f3e5607c

This should fix the issue. Let us know if it doesn't, once available.
