### ISSUE TITLE
Storage node remains idle since Disk Space Remaining < 1MB

### ISSUE THREAD

**Issue by phpbg** [storj/storj#3587]
Since my node reached 100% used disk space, it seems to remain idle: no egress, no delete, no ingress (there is free space on disk, but quota reached).

It is online and successful audits periodically happen, but I expected at least some egress, and maybe some delete+ingress...

Logs shows no error. Is this expected?

**Comment by kaloyan-raev** [comment]
@stefanbenten do you know if this is normal, considering the current network usage?

**Comment by DaBeSoft** [comment]
Just chiming in because i am observing similar behavior and just want to know if everything is normal.

The space given to storj is full (about 1.5TB, "Disk Space Remaining -10.00MB"). The physical disk itself still has some space left. As far as i can see, there was no ingress at all in the last month (Ingress: 0B), since there is no space. 

I have about 2GB Egress Traffic, some MB Repair Traffic and some KB Audit traffic a day, every day according to the Web Dashboard. 

Is it normal that for almost a month no deletes happened?

**Comment by kaloyan-raev** [comment]
Perhaps, the current usage pattern is to upload some data, then download it to see if it is there and then leave it for storage. Then occasionally download parts of the data.

If your storage is full then you won't utilize the bandwidth for uploading new data and for its initial download.

If you see incoming Audit traffic then your storage node is fine. We cannot predict how often the data will be downloaded by users, or when they would delete it.

**Comment by stefanbenten** [comment]
@kaloyan-raev That is more or less exactly it. As the initial target is large file storage / archival storage, the amount of egress is not going to explode or be huge.
