### ISSUE TITLE
storagenode/dashboard: responsive design

### ISSUE THREAD

**Issue by julio-matarranz** [storj/storj#3691]
Hello,
Thank you for the work done on the Dashboard.
But it would be great to be able to open the Dashboard on small phones (4") without rendering issue.
Could you find out what is the problem ?
Thank you.

**Comment by iglesiasbrandon** [comment]
Hey, @julio-matarranz; Brandon the Product Manager here from Storj Labs. Thank you bringing this up. A few of our community members have also brought this up and we have put it on our product roadmap. Unfortunately, we haven't had a chance to work on it yet but if you want to stay up to date with its status please follow the idea on our ideas portal. https://ideas.storj.io/ideas/V3-I-62 

Please keep your suggestions flowing so that we can continue to make this a better experience!

**Comment by julio-matarranz** [comment]
Hi @iglesiasbrandon,
Thank you for your answer.
I didn't have in mind that there's https://ideas.storj.io/ideas.

Btw, it would be nice to use https://github.com/storj/storj/milestones to know what would be in the next versions.

**Comment by stefanbenten** [comment]
@julio-matarranz You might be interested in this:
https://storjlabs.aha.io/published/01ee405b4bd8d14208c5256d70d73a38?page=4

**Comment by julio-matarranz** [comment]
@stefanbenten Thank you for the link :)
