### ISSUE TITLE
Error Creating Second Project on Tardigrade

### ISSUE THREAD

**Issue by modenero** [storj/storj#3710]
Not sure where to post this, but I'm really glad to see you guys back up and running, would love to get 2 of my new project on your platform, but the 2nd one is failing when I try to create it.

![Storj Error](https://i.imgur.com/OPvZZfm.png)

---

edit: also, are there any nodejs libraries yet for Tardigrade?

**Comment by stefanbenten** [comment]
Hey @modenero ! During Alpha and Beta, all users are limited to a single project. Interestingly, the error message should be more clear normally. Thank you for bringing this to our attention, I am bringing that up to the correct team to get it sorted out!

**Comment by stefanbenten** [comment]
This error message is properly fixed by #3712 
I am going to close this, as the project limitation was sent our together with the joining information.

**Comment by Carlotronics** [comment]
Hey @stefanbenten, sorry to reopen this old issue but it seems that it is not totally solved: I can't manage to create a second project, even with a simple name (such as `Project`). I always get the error `Network error: Response not successful: Received status code 500`. However, it seems to me that Storj / Tardigrade is no longer in beta? Is it still the expected behavior?
In any case, error 500 is not very clear and doesn't help me understand the problem.
![storj unable to create project](https://user-images.githubusercontent.com/21059490/103379027-8936c900-4ae4-11eb-9703-c45a74be353e.png)

**Comment by andriikotko** [comment]
It might happens if you have no payment method added and your balance is negative. In that case stripe return us 400 and we show to user this general 500 notification
