### ISSUE TITLE
storagenode-updater version error

### ISSUE THREAD

**Issue by Kaallee** [storj/storj#3730]
The updater reports parsing errors in the log _C:\Program Files\Storj\Storage Node\storagenode-updater.log_

`downloading versions from https://version.storj.io`
`version error: strconv.ParseUint: parsing "": invalid syntax`

**Comment by mniewrzal** [comment]
Hey @Kaallee 
Thank you for reporting this. You are seeing this error because storagenode-updater is trying to check if a newer version is available but or version server doesn't contain information about version yet. You can ignore this error for now and I will notify people responsible to add necessary entries to avoid throwing this error.

**Comment by littleskunk** [comment]
Fix deployed.
