### ISSUE TITLE
The satellite doesn't update the information that node have free space again

### ISSUE THREAD

**Issue by xfilokolo** [storj/storj#3744]
Hi, I noticed something interesting. When the allocated disk space becomes 100% full (sometimes it is even exceeded by several MB), the amount of traffic performed by the node drops drastically to almost zero. After some time, when some space is freed, the node still transmits very little data. It just helps restart the container. Immediately after this traffic returns to an average of 10-15 Mbps.

**Comment by stefanbenten** [comment]
This is intentional behaviour. The nodes are not instant reporting their free space to the satellite, or rather the satellite checks it for every request. It keeps a value for x minutes. With a restart of your node you force the node reaching out to update that value.
We have for that specific reason the note in the docs, that you should have at least 10% additional space on your disk (for the housekeeping and the potential overflow).

**Comment by xfilokolo** [comment]
@stefanbenten thank your for fast reply, but on two of my nodes this condition does not last for a few minutes or hours, but a few days.
