### ISSUE TITLE
Q: Can i keep files storj stored despite not running local node

### ISSUE THREAD

**Issue by hivemall** [storj/storj#3754]
i read https://github.com/storj/storj/wiki and are severely disappointed:

>  This tutorial assumes you have an account on a running Satellite and uses a test network Satellite by default.

use-case: upload a file to the uncensorable network, then prepay the hosting nodes and leave, just to come back 2 years later and retrieve the file (if the prepay estimate has not run out). 

How to achieve this without accounts/email-signups/continuous_run_local_node are not an option. I just want to drop a file and prepay in a cryptocurrency!

Please is/when this functionality available?

**Comment by egonelbre** [comment]
Running a local node is for people who desire to offer their own storage to the network, so it doesn't help you store data.

Usage of a Satellite is required for using Storj Network and our Tardigrade Satellites require registration. This is so that you can manage your projects, buckets and such with having a nice interface. It's possible that there will be third-party satellites that do not require it, however I haven't seen anyone developing one.

Crypto-currency payments are in the near road-map through STORJ tokens. So you will be able to only use tokens for payments.
