### ISSUE TITLE
Provide a systemd.service file for the gateway

### ISSUE THREAD

**Issue by jernst** [storj/storj#3757]
This will make it much more likely package maintainers like myself will consider including storj into their Linux distros.

**Comment by jeremyfritzen** [comment]
I tried to create a systemd.service but it doesn't work...

here is my code:
````
[Unit]
Description=S3 Gateway for tardigrade storage
After=network-online.target

[Service]
Type=simple

User=root
Group=root
UMask=007

ExecStart="/opt/gateway_linux_amd64 run"

Restart=on-failure

# Configures the time to wait before service is stopped forcefully.
TimeoutStopSec=300

[Install]
WantedBy=multi-user.target
````

I already tried the script and it works very well.
But when I launch the "systemctl start ..." command, it doesn't work.
The "systemctl status ..." command gives me the following:

> Warning: The unit file, source configuration file or drop-ins of tardigrade_storage.service changed on disk. Run 'systemctl daemon-reload' to reload units.
> ● tardigrade_storage.service - S3 Gateway for tardigrade storage
>    Loaded: loaded (/etc/systemd/system/tardigrade_storage.service; enabled; vendor preset: enabled)
>    Active: failed (Result: exit-code) since Sun 2020-02-16 11:48:22 CET; 41min ago
>   Process: 38737 ExecStart=/opt/gateway_linux_amd64 run (code=exited, status=203/EXEC)
>  Main PID: 38737 (code=exited, status=203/EXEC)
> 
> Feb 16 11:48:22 nextcloud.mariage-caribous.ovh systemd[1]: Starting S3 Gateway for tardigrade storage...
> Feb 16 11:48:22 nextcloud.mariage-caribous.ovh systemd[1]: tardigrade_storage.service: Main process exited, code=exited, status=203/EXEC
> Feb 16 11:48:22 nextcloud.mariage-caribous.ovh systemd[1]: tardigrade_storage.service: Failed with result 'exit-code'.
> Feb 16 11:48:22 nextcloud.mariage-caribous.ovh systemd[1]: Failed to start S3 Gateway for tardigrade storage.

Any idea on how to create this systemd.service file in order to start the gateway as a service at boot?

**Comment by jernst** [comment]
Here is what we just implemented for the [UBOS](https://ubos.net/) distro:

* [systemd.service](https://github.com/uboslinux/ubos-packages/blob/master/storj/systemd/storj-gateway.service), which invokes a shell script like this:
```
/usr/bin/gateway_linux_amd64 --config-dir /etc/storj $@
```
(basically it just adds a `--config-dir <dir>` argument) so that we can maintain the Storj configuration in `/etc/storj`, as good daemons are supposed to, as opposed to root's home directory. We wrap all other Storj commands in the same way, and add them to `/etc/sudoers.d` so that a non-root user can create those files.

P.S. systemd hinted to you that you should have invoked `systemctl daemon-reload` first :-)

**Comment by stefanbenten** [comment]
@jernst You do not have to specify the config-dir flag if you ran `gateway setup` with the user as which the systemd service runs the gateway as. This is because our `gateway setup` will create a config in relative to the home directory for the user, which normally is `~/.local/share/storj/gateway/`.
Would you mind opening a PR against the new repository of the gateway (https://github.com/storj/gateway) with your systemd file?

I am going to close this issue here, as mentioned above, the gateway has a new "home".
