### ISSUE TITLE
Account Balance USD $1417994505.00 for 8GB

### ISSUE THREAD

**Issue by Th3Van** [storj/storj#3766]
Looks like the billing system are a slightly off, at least on the Europe west satellite : 

![billede](https://user-images.githubusercontent.com/18688983/73395421-c0529800-42df-11ea-8476-717c20683cea.png)

Username : th3van@storj.dk

**Comment by littleskunk** [comment]
The issue here is a wrong conversion for the egress traffic. The issue is fixed but we had other problems with the coupon usage. At some point we decided to deploy the satellites with a broken version because of some performance improvements.

The final version should get deployed soon. That should fix it.

**Comment by littleskunk** [comment]
New version is deployed. Issue should be fixed. Please retry.

**Comment by Th3Van** [comment]
Yup, new version fixed the issue, thanks.

![billede](https://user-images.githubusercontent.com/18688983/73438471-5e7d4700-434e-11ea-8dec-49ef721b7b35.png)
