### ISSUE TITLE
Not a valid Win32 application

### ISSUE THREAD

**Issue by tokinol** [storj/storj#3775]
When trying to use the gateway for Windows application gateway_windows_amd64.exe on a 2003 server 64 bit, it won't start at all. Error message is that it is not a valid Win32 application.

Upgrading that server is not an option at this time due to proprietary software on it requiring still 2003 server.

**Comment by egonelbre** [comment]
Currently we support the same versions as Microsoft, since we rely on the security of the underlying system. Currently this means for desktop Windows 8.1 and above, and Windows 2012 and above. The software may run on earlier, but we don't really support them. I do empathize with having to deal with software that has not been updated.

It could be possible to get things running on Windows 2003 with an older Go version and modifying the source code *I would advise against it*, due to security concerns.

My recommendation would be to start a separate linux server (or a VM) with gateway running on it.
