### ISSUE TITLE
latest s3 gateway CommonPrefixes format error 

### ISSUE THREAD

**Issue by dassio** [storj/storj#3804]
current latest s3 gateway list-objects response CommonPrefixes format wrong:
```

danny@danny:~/tools$ ./gateway version 
2020-03-16T00:39:55.209Z        INFO    Configuration loaded from: /home/danny/.local/share/storj/gateway/config.yaml
Release build
Version: v0.34.6
Build timestamp: 04 Mar 20 14:23 UTC
Git commit: 253150a5f408d7a4fa3d8bec2a37c6f9472a92a2
```

current list-object response:

>    "CommonPrefixes": [
>         {
>             "Prefix": "papers/"
>         },
>         {
>             "Prefix": "constraint programming/"
>         },
>         {
>             "Prefix": "Temporal Logic/"
>         },
>         {
>             "Prefix": "FSM/"
>         },
>         {
>             "Prefix": "Cucumber/"
>         }
>     ]

expected response:

> 
> "CommonPrefixes": [
>         {
>             "Prefix": "MBT/papers/"
>         },
>         {
>             "Prefix": "MBT/constraint programming/"
>         },
>         {
>             "Prefix": "MBT/Temporal Logic/"
>         },
>         {
>             "Prefix": "MBT/FSM/"
>         },
>         {
>             "Prefix": "MBT/Cucumber/"
>         }
>     ]
>     

#3802

**Comment by ifraixedes** [comment]
@dassio thanks for reporting it, however, we currently have a specific repository for S3 gateway (https://github.com/storj/gateway), would you mind to open the issue in its repository, please?

**Comment by dassio** [comment]
there is no issue with that repository, currently  the generated build  is from this repository, until removed completely from stroj/cmd/gateway, i think it should stay here

**Comment by ifraixedes** [comment]
I'm closing this issue, please reopen it in [storj/gateway repository](https://github.com/storj/gateway).

At that time, I warned you to open it there because we were in a transition and I believed that it would have got attention and you should have got a faster response than having in this repository.

Recently, we moved our release process for the gateway over [storj/gateway](https://github.com/storj/gateway) repository so this repository doesn't contain anything related to the gateway.

Thanks for reporting it.
