### ISSUE TITLE
OpenBucket with default EncryptionAccess causes panic in ListObjects

### ISSUE THREAD

**Issue by jburnett** [storj/storj#3841]
Passing default EncryptionAccess to OpenBucket results in valid *Bucket, but future code using it will panic.  Should OpenBucket validate EA's store != nil?

>	b, err := p.OpenBucket(s.localCtx, bucketName, &uplink.EncryptionAccess{})
	if err != nil {
		return nil, err
	}
	ol, err := b.ListObjects(s.localCtx, &uplink.ListOptions{
		Prefix:    "/",
		Cursor:    "",
		Recursive: false,
		Direction: storj.After,
	})
	if err != nil {
		return nil, err
	}

> panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x944017]
goroutine 1 [running]:
github.com/spacemonkeygo/monkit/v3.newSpan.func1(0xc00011c250)
	/home/jb2/go/pkg/mod/github.com/spacemonkeygo/monkit/v3@v3.0.5/ctx.go:145 +0x396
panic(0xaca2a0, 0x11389a0)
	/snap/go/5569/src/runtime/panic.go:973 +0x3e3
github.com/spacemonkeygo/monkit/v3.newSpan.func1(0xc00011c280)
	/home/jb2/go/pkg/mod/github.com/spacemonkeygo/monkit/v3@v3.0.5/ctx.go:145 +0x396
panic(0xaca2a0, 0x11389a0)
	/snap/go/5569/src/runtime/panic.go:973 +0x3e3
storj.io/common/encryption.(*Store).LookupUnencrypted(0x0, 0xc000122308, 0x6, 0xc00012230f, 0x0, 0x44b79c, 0x8, 0xa8c360, 0x1)
	/home/jb2/go/pkg/mod/storj.io/common@v0.0.0-20200401122855-4ad28fd2218f/encryption/store.go:185 +0x37
storj.io/common/encryption.DerivePathKey(0xc000122308, 0x6, 0xc00012230f, 0x0, 0x0, 0x1, 0xc000122320, 0x8)
	/home/jb2/go/pkg/mod/storj.io/common@v0.0.0-20200401122855-4ad28fd2218f/encryption/path.go:241 +0x77
storj.io/uplink/private/metainfo/kvmetainfo.(*DB).ListObjects(0xc00013e080, 0xc9c6a0, 0xc000138b40, 0x0, 0x0, 0xc000122278, 0x6, 0x0, 0x0, 0x0, ...)
	/home/jb2/go/pkg/mod/storj.io/uplink@v1.0.3/private/metainfo/kvmetainfo/objects.go:199 +0x34e
storj.io/storj/lib/uplink.(*Bucket).ListObjects(0xc000144000, 0xc9c4e0, 0xc000040118, 0xc0000f7be0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/jb2/go/pkg/mod/storj.io/storj@v1.1.1/lib/uplink/bucket.go:129 +0x210
bitbucket.org/jburnett/tguno/internal.(*StorjProvider).ListObjects(0xc000033180, 0x7fff0c7f5e2d, 0x6, 0x1f, 0xc000033180, 0x0)

**Comment by stefanbenten** [comment]
@jburnett Thank you for bringing this to our attention, we are looking into this!
I'll keep you updated!

**Comment by kaloyan-raev** [comment]
@jburnett instead of passing `&uplink.EncryptionAccess{}` you should use the constructor function `NewEncryptionAccess()`: https://godoc.org/storj.io/storj/lib/uplink#NewEncryptionAccess

This will initialize the internal state of `EncryptionAccess` properly.

Also, note that you are using the v0.x uplink API that will be deprecated officially very soon. We recommend to move to the new v1.x API: https://github.com/storj/uplink

**Comment by jburnett** [comment]
Thanks for your feedback. I had changed to using NewE...A..., but would prefer other devs get appro err on OpenBucket.  It took me a while to figure out that ListObject's error was actually due to invalid EA passed to OpenBucket.  Is it easy enough to add a param validation check to OpenBucket?

BTW, confirmed that go.mod refs updated pkgs:
```
	storj.io/common v0.0.0-20200401122855-4ad28fd2218f
	storj.io/storj v1.1.1
	storj.io/uplink v1.0.3 // indirect

```

**Comment by zeebo** [comment]
I've created https://review.dev.storj.io/c/storj/storj/+/1717 to address this issue. It should now return an error instead of throwing a panic from a distant land.

That said, I'd like to reiterate that it would be in your best interest to only use the [storj.io/uplink](https://pkg.go.dev/storj.io/uplink) API if possible, and please let us know if you have any challenges doing that. I wasn't able to find a way to trigger the same panic from that API.
