### ISSUE TITLE
Storage node service fails to start if local port is blocked but no any errors in logs

### ISSUE THREAD

**Issue by MaxMaximus** [storj/storj#3856]
Hello.

Today I was installing another new storage node (Windows GUI, ver 1.1.1).
First i encounter setup failure due to disabled windows built-in firewall service (there is a 3rd party firewall installed and so built-in one is disabled). It is old known issue: https://github.com/storj/storj/issues/3759
I was thinking it already fixed, but looks like it still here...

After enabling windows firewall and repeat of install process from the beginning it failed again at stage when setup try to start installed service. (The process was terminated unexpectedly)
After few more tries and some experiment if have found the reason: storage node service refuse to start because it can not open port for incoming connection. It was blocked by firewal (i use strict policy: all network activity is blocked by default unless it allowed by explicit rules). I forgot to add a firewall rule (actually not forgot but was planning to do it after program installation not before).
More importantly there is no any errors in log files if program fails due to blocked port. After first failure i have cheeked the log and only found this:
``` 
2020-04-15T00:25:20.438+0300	INFO	Configuration loaded from: D:\Storj_Data\Storage Node\config.yaml
2020-04-15T00:25:20.490+0300	INFO	Operator email: xxxx
2020-04-15T00:25:20.490+0300	INFO	operator wallet:  xxxx 
```
That is all - after it process just exits silently.

Later i have tried to start node from a command line, and it gives clear reason why it can not start:
`Error: listen tcp :28967: listen: An attempt was made to access a socket in a way forbidden by its access permissions.`
But this error only visible from CLI, user can not see it from regular GUI/windows service start.

**Comment by ifraixedes** [comment]
@MaxMaximus thanks for reporting.

> First i encounter setup failure due to disabled windows built-in firewall service (there is a 3rd party firewall installed and so built-in one is disabled). It is old known issue: #3759
I was thinking it already fixed, but looks like it still here...

The issue that you mention should be updated once it is released. On the other hand, I've checked the changelog for Storage Node in the [release v1.1.1](https://github.com/storj/storj/releases/tag/v1.1.1) and there isn't any entry referencing to it.
It's good that you check anyways because we may miss updating the corresponding issues if it doesn't disturb you.

> After enabling windows firewall and repeat of install process from the beginning it failed again at stage when setup try to start installed service. (The process was terminated unexpectedly)
After few more tries and some experiment if have found the reason: storage node service refuse to start because it can not open port for incoming connection. It was blocked by firewal (i use strict policy: all network activity is blocked by default unless it allowed by explicit rules). I forgot to add a firewall rule (actually not forgot but was planning to do it after program installation not before).
More importantly there is no any errors in log files if program fails due to blocked port. After first failure i have cheeked the log and only found this:
> 
> 2020-04-15T00:25:20.438+0300	INFO	Configuration loaded from: D:\Storj_Data\Storage Node\config.yaml
2020-04-15T00:25:20.490+0300	INFO	Operator email: xxxx
2020-04-15T00:25:20.490+0300	INFO	operator wallet:  xxxx 
That is all - after it process just exits silently.
> 
> Later i have tried to start node from a command line, and it gives clear reason why it can not start:
Error: listen tcp :28967: listen: An attempt was made to access a socket in a way forbidden by its access permissions.
But this error only visible from CLI, user can not see it from regular GUI/windows service start.

It looks weird.

Can you please tell us if you have redirected the logs to some file and the command that you're using to see them?

This mainly a double check that you are following what's commented in https://documentation.storj.io/resources/faq/check-logs

Thanks for your patience.

**Comment by MaxMaximus** [comment]
No, i do not use any log redirect. 
Log located in the default place for windows GUI client (C:\Program Files\Storj\Storage Node\storagenode.log). In the same folder with app's executable itself and config file.
Logging level is also default:
``log.level: info``
But no any logs entries about blocked ports. Errors shown only if app lunched from console/command prompt. 

Also, there is similar issue (only mirror/reverse) with CLI calls to CLI/text dasboard: if there is some errors in command line (like wrong paths to identity or config files) errors messages are written to the log file instead of sending it back to console. For example i call app from CLI wit command line:
``storagenode.exe dashboard --config-dir "C:\Program Files\Storj\Storage Node"``
And app starts and exits silently without any messages in console.
But it i open the log files there is a reason why command was not executed:
```
2020-04-19T05:21:50.279+0300	INFO	Configuration loaded from: C:\Program Files\Storj\Storage Node\config.yaml
2020-04-19T05:21:50.479+0300	FATAL	file or directory not found error: open C:\Users\Max\AppData\Roaming\Storj\Identity\Storagenode\identity.cert: The system cannot find the path specified.
```
Same with using CLI commands exit-satellite and exit-status. All error are written to logs only.

**Comment by MaxMaximus** [comment]
Oh, i have found the source if issues with CLI version (why error messages went into logs instead of console). It is due to this string in the config file:
```
# can be stdout, stderr, or a filename
log.output: winfile:///C:\Program Files\Storj\Storage Node\\storagenode.log
```
I did not put it here (it was added automatically during node GUI setup) so I did not even know that it exist.
It can explain why some CLI commands outputs is partially redirected from console to log file.
I guess i need to use separate config files for GUI/service and for CLI next time.

But it does not explain why errors about blocked ports from running windows service from default GUI setup shown in console only instead of log files.

**Comment by zeebo** [comment]
Let my start off by by saying wow do we have some convoluted code around logging errors.

With that out of the way, I believe what you experienced comes down to this section of code:

https://github.com/storj/private/blob/086ae18ff1774551b65f089b17d7b36a55987194/process/exec_conf.go#L364-L369
```go
		err = workErr
		if err != nil {
			logger.Debug("Unrecoverable error", zap.Error(err))
			fmt.Println("Error:", err.Error())
			os.Exit(1)
		}
```

along with

https://github.com/storj/storj/blob/5a85e8d749d354737bf86f5d5517dc8615999ab7/cmd/storagenode/main.go#L146-L149

Basically, if you're unable to load the identity file, it doesn't bubble up an error to the common error handling path that logs it in debug and prints it before exiting, and it just directly calls `log.Fatal`.

Secondly, the common error handling code logs the error in debug, so unless your log level is set to include it, it doesn't show up in the logs.

With that out of the way, it's not clear what the right fix for this is, because this code is shared across a lot of our binaries, and they all have different desires. The `uplink` command, for example, has stronger requirements around having a good user experience for errors. So what I'm going to try to do is to change that to just do `log.Fatal` and see how that goes.

**Comment by zeebo** [comment]
Alright, I pushed up https://review.dev.storj.io/c/storj/private/+/1720 to make it so that the error is always printed somewhere visible at least.
