### ISSUE TITLE
Docker os.rename( source, dest ) fails on different --mount points

### ISSUE THREAD

**Issue by Sembeth** [storj/storj#3864]
Hello,
thank you for your time.

There seems to be a bug in Docker with os.rename( source, dest ) and --mount.

How did I found out:
I‘m a SNO and my Server has SSDs in a raid where the operation system is running. Size 900GB free.
I have a volume that's running HDDs in raid. Currently 40TB free.

I would like that in the Docker container 
„/app/config“ 
folder is mounted on the SSD. 
Therefore the SQLite database files and folders like
„/app/config/storage/trash“ 
„/app/config/storage/temp“ 
„/app/config/storage/garbage“ 
on the SSD.

I then want only the folder „app/config/storage/blobs“ to be mounted on the volume with the HDDs.

Since there is still no way to configure this in config.yaml or elsewhere I thought I would just extend the Docker run command a bit like this

docker run 
-d 
--restart unless-stopped 
-p 28967:28967 
-p 14002:14002 
-e WALLET="***" 
-e EMAIL="***" 
-e ADDRESS="***:28967" 
-e STORAGE="20TB" 
--mount type=bind,source="/docker/storagenode/identity",destination=/app/identity 
--mount type=bind,source="/SSDVolume/node",destination=/app/config 
--mount type=bind,source="/HDDVolume/blobs",destination=/app/config/storage/blobs 
--name storagenode storjlabs/storagenode:beta

Why?
I have noticed that the database files are often written to and also that the „/app/config/storage/temp“ folder is written often to. Therefore I would like to move those to the SSD. And just keep the „/app/config/storage/blobs“ on the HDDs, because they need a lot of space.

Problem:
I get the following Error:
2020-04-25T15:48:07.996Z        ERROR   piecestore      upload failed   {"Piece ID": "L5V5P3NQIVMWHBFVINRHRJXEUW4EUATK3UY4TYIOWDBMTM3LJUTQ", "Satellite ID": "1wFTAgs9DP5RSnCqKV1eLf6N9wtk4EAtmN5DpSxcs8EjT69tGE", "Action": "PUT", "error": "pieces error: filestore error: rename config/storage/temp/blob-131610207.partial config/storage/blobs/pmw6tvzmf2jv6giyybmmvl4o2ahqlaldsaeha4yx74n5aaaaaaaa/l5/v5p3nqivmwhbfvinrhrjxeuw4euatk3uy4tyiowdbmtm3ljutq.sj1: **invalid cross-device link**", "errorVerbose": "pieces error: filestore error: rename config/storage/temp/blob-131610207.partial config/storage/blobs/pmw6tvzmf2jv6giyybmmvl4o2ahqlaldsaeha4yx74n5aaaaaaaa/l5/v5p3nqivmwhbfvinrhrjxeuw4euatk3uy4tyiowdbmtm3ljutq.sj1: invalid cross-device link\n\tstorj.io/storj/storage/filestore.(*blobWriter).Commit:105\n\tstorj.io/storj/storagenode/pieces.(*Writer).Commit.func1:130\n\tstorj.io/storj/storagenode/pieces.(*Writer).Commit:198\n\tstorj.io/storj/storagenode/piecestore.(*Endpoint).doUpload:419\n\tstorj.io/storj/storagenode/piecestore.(*drpcEndpoint).Upload:215\n\tstorj.io/common/pb.DRPCPiecestoreDescription.Method.func1:987\n\tstorj.io/drpc/drpcmux.(*Mux).HandleRPC:107\n\tstorj.io/drpc/drpcserver.(*Server).handleRPC:105\n\tstorj.io/drpc/drpcserver.(*Server).ServeOne:56\n\tstorj.io/drpc/drpcserver.(*Server).Serve.func2:93\n\tstorj.io/drpc/drpcctx.(*Tracker).track:51"}

If you google for „**invalid cross-device link**“ it seems like that there a problem with Docker and os.rename( source, dest )

https://gist.github.com/var23rav/23ae5d0d4d830aff886c3c970b8f6c6b

https://giedrius.blog/2018/01/28/why-os-move-sometimes-does-not-work-and-why-shutil-move-is-the-savior/

https://stackoverflow.com/questions/42392600/oserror-errno-18-invalid-cross-device-link

Could one change 
os.rename (source, dest) 
to 
shutil.move()
or 
shutil.copy() and os.remove()
and test it with the --mount command?

I would also like to see that we can configure the location of the database files and the "blobs/temp/trash/garbage" folder as we wish.

Thank you very much.

**Comment by egonelbre** [comment]
`storage/temp` is used to write data that is being uploaded. It would write directly to `storage/blobs` however that would complicate things with atomicity. The `temp` must be in the same disk as `blobs`, because we need the data to move atomically from

**Comment by egonelbre** [comment]
The same goes about garbage. We are still tweaking things and in the future, the garbage folder will contain less data, moving it to a separate disk would add a lot of disk operations that probably aren't that useful.

**Comment by Sembeth** [comment]
Hello and thank you very much for your time.

I assume that when someone uploads data to me, they upload it in little chunks. Because they may have slow upload speeds. So the data written to `/storage/temp` will require many IOPs.

If the file was uploaded to `/storage/temp` and is only moved to `/storage/blobs`, not many IOPs should be needed.

Maybe this would also be helpful for people who use SMR drives. #3854 

I would just really like to see the option for people who want to optimize their setup.

**Comment by egonelbre** [comment]
@Sembeth yes, I'm currently looking at that issue and seeing whether a simple change would fix it.

**Comment by Sembeth** [comment]
I have something to add.

I have created this issue because there seems to be a bug in Docker and multiple --mount commands with os.rename. And not to find a more optimized setup.

Even if I only use one HDD and change the location of 
`/storage/blobs` to `/HDDvolume/blobs` 
with one `--mount` command
and 
`/storage/temp` to `/HDDvolume/temp` 
with another `--mount` command.

Somethink like a os.rename dosen't work anymore. 

So I would have hoped that you could debug the behaviour and change and test it in os.move or os.copy and os.delete.

Thank you very much for your time.

**Comment by egonelbre** [comment]
The `rename` cannot be directly translated to a `copy` and `delete` due to the atomic requirements of the move. This would introduce another folder "temptemp" (for lack of a better folder) that would be required to be on the same folder to support atomic move. This of course would suffer the same issues as you already listed.

Maybe the name of the folder could've been better to indicate the meaning - i.e. "staging" or something, but that rename wouldn't probably improve the situation significantly.

**Comment by zeebo** [comment]
I agree with @egonelbre that I don't think it makes much sense to support the `temp` and `blobs` folders to be on different drives.

That said, I hope to get in changes to allow configuring the database path to be somewhere else (https://review.dev.storj.io/c/storj/storj/+/1716) and add some in memory buffering on the nodes for uploads (https://review.dev.storj.io/c/storj/storj/+/1719).

Once those are in, perhaps we can re-evaluate the desire to have them be on different drives and close this issue?

**Comment by Sembeth** [comment]
@zeebo in memory buffering and changing the location of the database both sound amazing.

I still think there might be potential for different locations of `temp' and `blobs'.

Most of the SNOs are home users. Anyone who builds their own server/NAS will buy an SSD for the operating system and multiple HDDs in a raid for data.

So it makes sense for me to use the SSD or at least have an option for it.

Just out of curiosity: Why do you need an atomic rename instead of copy / remove?

**Comment by egonelbre** [comment]
There are few properties that are really useful:
1. once it has committed the data to disk, it should be ready to serve
2. it should not serve data that has not been committed

These are useful properties to have. Let's say it just happens that download to temp on a different disk succeeds and move to the other one fails, what should happen?

We can have two potential implementations with regards to the write cache:
1. Storage node immediately confirms with a signature after storing the data in temp and before moving. And later fails an audit which causes the storage node to be failed.
2. Storage node waits for the move to finish, which means it would end up more likely to be part of the long-tail cancellation.

Note, case 1 would still involve some sort of temporary folder to move to first and then atomic rename to preserve the "atomic" rename property.

Case 1, could potentially end up damaging a lot of segments, because the storage node would be still accepting uploads and keeping them on the temp folder. This means there now needs to be a way to recover from this situation.

Case 2, would also decrease the upload speed due to having to wait for the final copy to the other disk.

Basically neither these scenarios are great and significantly increase the complexity.

There of course is also possibility to use some other way to create this "atomicness", e.g. a separate database, however this adds additional latency to the download queries. Alternatively preserve on temp drive until they can be moved to some other drive.

Just to clarify, I'm definitely not saying it's not possible to do. Basically, this change would significantly increase the complexity of the system. It's feasible that in the future we'll have some sort of write cache disk option to allow larger and faster inbound load (no promises).

I think at the moment having an in-memory buffer will be a better trade-off in terms of complexity of implementation and the potential gains.

I'm closing this for now, because I don't think we'll get to changing this any time soon. But, I did create an internal issue as a note for the future.
