### ISSUE TITLE
Update your Node to Version v1.3.3

### ISSUE THREAD

**Issue by victorelec14** [storj/storj#3868]
The docker does not update to the latest version of the tag: beta remains in v1.1.1.

It seems that the new image has not been uploaded?

Should I use the tag: latest or continue with the tag: beta?

![image](https://user-images.githubusercontent.com/543450/80531618-375d0280-899b-11ea-8e8b-047812843358.png)

**Comment by ifraixedes** [comment]
@victorelec14 thanks for reporting.

The docker image for v1.3.1 isn't intentionally published yet.
We roll out the releases in batches because the docker image doesn't use our updater (currently only the Windows storage node uses it) and that means that we cannot limit the number of Storages Nodes are updated, we wait until we roll out the new version to the Windows Storage Nodes and then we publish the docker image of it.

> Should I use the tag: latest or continue with the tag: beta?

We did a change last week to publish the last version under `latest` (and also the under `beta`) and we should publish the `v1.3.1` under that docker tag.
So far, the last stable version published is `v1.1.1` and that is under the `beta` tag so don't change to `beta` tag now, you should do it after the `v1.3.1` gets published.
