### ISSUE TITLE
Too many canceled uploads

### ISSUE THREAD

**Issue by littleskunk** [storj/storj#3879]
My log is full with upload canceled but my used space keeps increasing very fast. I noticed that even repair uploads are canceled which makes no sense because there is no cancelation.
```
2020-05-08T21:26:14.997Z        INFO    piecestore      piecestore/endpoint.go:316      upload started  {"Piece ID": "26H22TD6PI5NQUM47PQ7JRHSLMADCBF5SL2B3M6UR6QXFVTN4UEQ", "Satellite ID": "12L9ZFwhzVpuEKMUNUqkaTLGzwY9G24tbiigLiXpmZWKwmcNDDs", "Action": "PUT_REPAIR", "Available Space": 5689929559552}
2020-05-08T21:26:15.000Z        INFO    piecestore      piecestore/endpoint.go:300      upload canceled {"Piece ID": "26H22TD6PI5NQUM47PQ7JRHSLMADCBF5SL2B3M6UR6QXFVTN4UEQ", "Satellite ID": "12L9ZFwhzVpuEKMUNUqkaTLGzwY9G24tbiigLiXpmZWKwmcNDDs", "Action": "PUT_REPAIR"}
```

What is the difference between `uploaded` and `upload canceled`? Why do we print out different log messages? I would like to optimize my storage node to offer the best performance. Upload canceled sounds like something I should try to avoid. -> We need better logging.

**Comment by litori** [comment]
Also noticing that upload canceled pieces would take up space on the node.  How do I free up space caused by canceled pieces?

**Comment by littleskunk** [comment]
The solution is better logging. These pieces are not canceled. The log message is wrong.

**Comment by Robertomcat** [comment]
(El mensaje que escribo aquí abajo, es el mismo que he escrito en el foro oficial)

My cancellation rate is absolutely great.

My node has been active since May 5, and is running on an HPE ML110 G9 server, 64GB of RAM, the Windows server 2016 operating system is on a RAID 1 SSD (Managed with the b140i integrated controller), the storj data is hosted on a RAID5 8 × 10 TB (configuration is long overdue, And the disks are in two hotplug cages), these disks are managed through a P440 4GB hardware controller (the controller’s RAM memory is all dedicated to writing), the Internet connection is 600/600 and the server’s geographical location is in Valencia-Spain.

I have analyzed 990MB of logs since the node is up and running, and the result is this

![2020-06-16_21h07_47](https://user-images.githubusercontent.com/17690060/84931906-c2bd5f00-b0d3-11ea-81df-51eb2acdffa6.png)

**Comment by mobyvb** [comment]
Fix here: https://review.dev.storj.io/c/storj/storj/+/2234

**Comment by littleskunk** [comment]
I can confirm that the fix works. It will go out with with the next version.
