### ISSUE TITLE
Mismatch available space 

### ISSUE THREAD

**Issue by Quake4** [storj/storj#3880]
![image](https://user-images.githubusercontent.com/29517243/81904192-9b064300-95cb-11ea-984e-1c1ad0394d18.png)

100 Gb in Trash. Who is pay for it? Why isnt empty?

**Comment by ifraixedes** [comment]
@Quake4 thanks for reporting it.
We were aware of that bug and we fixed in the last release https://github.com/storj/storj/releases/tag/v1.4.2

Please keep it on eye once your node gets updated to the new version to see if the problem is fixed or not in your end and close or comment again on this ticket.

Thanks for you patience.

**Comment by Quake4** [comment]
![image](https://user-images.githubusercontent.com/29517243/82061881-f3276d00-96d1-11ea-961d-95f2c1f76d5a.png)

**Comment by Quake4** [comment]
I took some space away from node.
![image](https://user-images.githubusercontent.com/29517243/82839508-4cfd1380-9ed8-11ea-8f5b-0b4839dcd946.png)

**Comment by stefanbenten** [comment]
@Quake4 Is this issue still persistent?

**Comment by Quake4** [comment]
No
