### ISSUE TITLE
Garbage after GE

### ISSUE THREAD

**Issue by AlexandrTyshchenko** [storj/storj#3908]
I did GE on Stefan satellite on the past month, the garbage collector clean all files with .sj1 extension, but Stefan’s satellite folder contains also files without extension:

![image](https://user-images.githubusercontent.com/46418015/84371644-a5275b80-abe2-11ea-858a-c42d965f7c48.png)

And those files consume ~255GB

My expectation: it should be deleted because anyone not paying for this garbage. This is bug of the garbage collector.

**Comment by crawter** [comment]
Hey, @AlexandrTyshchenko! 

Thanks for reporting this issue!

Would you kindly share with us some additional info?
Like, your OS, storagenode version, logs, etc.

Have a great day!

**Comment by AlexandrTyshchenko** [comment]
Hi @crawter !

Thanks for your quick reply! 
Sure, I can share evrything that you need:
I using docker version of storage node on the latest Debian 10

`cat /etc/debian_version
10.4`
Storage node version: v1.5.2
Node ID:12TJ4mVGunUEQohSp6fXJjbzKmVeeNMbBq4NhmG76fmQB593f43
Storage [node log is here](https://drive.google.com/file/d/18XEgTbsyIRCtQc7pEVgC8dHHLSFmF8Kw/view?usp=sharing).

If you need any additional information, please let me know.

Have a good day!

**Comment by MaxMaximus** [comment]
Look at the dates (created/modified) of all these files. It all Summer of 2019 year.

They all should be deleted long ago in the total network wipe which happened somewhere in autumn of 2019. No data created before it should be stored on nodes. 
So a bug probable happened last year during network wipe. 
And i think current node and its garbage collector does not aware of these files exists at all.

**Comment by AlexandrTyshchenko** [comment]
In addition, I see the same situation on another node that also did GE on Stefan satellite.

![image](https://user-images.githubusercontent.com/46418015/84751747-96b3b800-afc5-11ea-9c68-d2b1e032cda6.png)

> Look at the dates (created/modified) of all these files. It all Summer of 2019 year.
> 
> They all should be deleted long ago in the total network wipe which happened somewhere in autumn of 2019. No data created before it should be stored on nodes.
> So a bug probable happened last year during network wipe.
> And i think current node and its garbage collector does not aware of these files exist at all.

I have a proposition: Maybe we should delete all files inside the satellite folder after the storage node successfully completes GE?

**Comment by ReneSmeekes** [comment]
It's not just a GE issue. I checked my folders as well and it turns out I have lots of these files as well. In fact about 80% of the files stored in the blobs folder for this satellite don't have the sj1 extension and are from summer 2019, taking up unpaid space.
The equation seems to get a little better when looking at used space. The entire folder is about 1.5TB and that size really hasn't changed since May as this satellite is pretty much idle at this point. However, in May I got paid for 780GB. So half of it is unpaid and will never be downloaded. I think we need a clean up in one of the following updates to free up this space.

stefan-benten doesn't seem to be the only effected satellite either. I'm also seeing some of these files in the v4weeab67sbgvnbwd5z7tweqsqqun7qox2agpbxy44mqqaaaaaaa folder, though not nearly as many.

If it helps.
Node ID: 12aYrWFmJqrmhN3zgkvANBTsj2DdLwf2aZC8T5t7CrNazHahKXW
Synology DS3617xs (DSM 6.2)
Node version: 1.5.2

**Comment by thepaul** [comment]
Note that there still can be valid piece files that don't have a .sj1 suffix. The new piece storage format indicated by .sj1 was introduced _after_ the network wipe, and some pieces were stored in FormatV0 beforehand.

I just don't want anyone to get the idea that all piece files with no extension are garbage.

The garbage collector is supposed to work on both types of storage, but yes there certainly might be a bug.

**Comment by ReneSmeekes** [comment]
Thanks for the response. I wasn't aware of that, but I wouldn't manually remove anything anyway.

The file dates seem to all be from Juli or early August 2019 though. This should be prior to the last network wipe (around august 22nd?). The fact that only about half of the used space is actually paid confirms that too. I'm not sure why garbage collection hasn't caught these pieces. I would have expected they would have been cleaned up by now as well. Let me know if I can provide any more information or test something to help out. 

I don't care about the used space since my node has never been full anyway, so I'm just interested on getting it resolved for the future and for those SNOs who are missing out on potential income right now.

**Comment by ReneSmeekes** [comment]
Looks like garbage collection is currently hard at work on stefan-benten satellite. Fix in progress?

**Comment by AlexandrTyshchenko** [comment]
I also see activity of garbage collector on one of my node:

![image](https://user-images.githubusercontent.com/46418015/84993879-88df6d80-b152-11ea-8124-fbdca583a053.png)

![image](https://user-images.githubusercontent.com/46418015/84994064-d0fe9000-b152-11ea-8c46-71642aeec0fb.png)

**Comment by ReneSmeekes** [comment]
I have to correct my previous statement. I was looking at the folders starting with numbers, but those seem to be processed at the end of the process and weren't done yet. It seems this garbage collection does clean up the remaining files.

There are still a few of those older files sticking around, but this is likely because of how garbage collection works with bloom filters that won't clean up 100% in one run. They'll be caught in subsequent runs no doubt.

This is what the ac folder for stefan-benten looks like now.
![image](https://user-images.githubusercontent.com/8392961/85120633-d11a9080-b223-11ea-8271-64abd2eca013.png)

So looks mostly cleaned up. Too bad almost all data is being removed by this garbage collection. End of an era for this satellite.

**Comment by Qweder93** [comment]
https://review.dev.storj.io/c/storj/storj/+/2245
https://review.dev.storj.io/c/storj/storj/+/2276
added to master will be in next releases!

**Comment by AlexandrTyshchenko** [comment]
@Qweder93 Thanks a lot!
I will let you know how it will be after this release will come to my node.

**Comment by AlexandrTyshchenko** [comment]
I can confirm, after update to v1.9.5 blob with the id that specified on the initial post is gone (deleted).
So, the issue was solved!
