### ISSUE TITLE
Storagenode API returns invalid disk space used when allocated-disk-space is below actually used space

### ISSUE THREAD

**Issue by felixbrucker** [storj/storj#3942]
With one of the recent releases it seems like the disk space used calculation changed: https://forum.storj.io/t/api-disk-space-used-negative/9133

As seen in the forum thread the used space of alexey is 270GB after the adjustment, which is incorrect. I myself have seen negative values as well, with no obvious way how they were calculated, same as for alexey.

**Comment by gbaker3** [comment]
I am also seeing strange used space reporting behaviour after the update to v1.12.3. With 3.36 TB allocated, the node is showing 3.39 TB used (the used space space was slightly more than allocated prior to v1.12.3, due to the updated rounding introduced in v1.11.1).  However the CLI and web dashboard show 339 GB available, This is, not coincidentally, the amount of physical space remaining on my drive. Fortunately the node doesn't seem to be trying to fill this space, since no new uploads are being started. The node has now had two opportunities to re-walk the storage and recalculate the space used.

Running in docker on Debian stretch arm64.

**Comment by profclems** [comment]
The commit that caused this issue was reverted here: https://github.com/storj/storj/commit/245986d528ee807c49a0dc0b365bd931094f0147
