### ISSUE TITLE
uplink: api key format error: invalid macaroon version

### ISSUE THREAD

**Issue by johackim** [storj/storj#4030]
Hello,

When I try to setup I have this error :

```
docker run -it storjlabs/uplink:latest
Select your satellite:
        [1] us-central-1.tardigrade.io
        [2] europe-west-1.tardigrade.io
        [3] asia-east-1.tardigrade.io
Enter number or satellite address as "<nodeid>@<address>:<port>" [1]: 2
Choose an access name (use lowercase letters) ["default"]: 
Enter your API key: <MY_API_KEY>
Data is encrypted on the network, with an encryption passphrase
stored on your local machine. Enter a passphrase you'd like to use.
Enter your encryption passphrase: 
Enter your encryption passphrase again: 

With your permission, Tardigrade can automatically collect analytics information from your uplink CLI and send it to Storj Labs (makers of Tardigrade) to help improve the quality and performance of our products. This information is sent only with your consent and is submitted anonymously to Storj Labs: (y/n)
n
Error: uplink: uplink: api key format error: invalid macaroon version
```

The API key is copy paste from `Generate Access Grant` directly from browser :

![screenshot](https://user-images.githubusercontent.com/5039608/105884707-873f2780-6008-11eb-9df7-c53a14612b22.jpg)

**Comment by jtolio** [comment]
We have a bit of a documentation issue - in the web wizard you selected "continue in the browser" to generate an access grant (which is not an API key), but then you are using the CLI workflow (if you go back in the access grant wizard, there's a "continue in CLI" setting that is used with uplink setup). If you want to use the access grant generated in the "continue in the browser" flow, you need to use uplink import instead of uplink setup. We'll be working to clean this up soon.

**Comment by johackim** [comment]
Thanks ;)
