### ISSUE TITLE
Uplink on homebrew?

### ISSUE THREAD

**Issue by exadeci** [storj/storj#4115]
Hello,

It would be nice to have `uplink` on homebrew for macos

**Comment by ifraixedes** [comment]
@exadeci thanks for your proposal

However, I'd like to invite you to post it in our Forum, in the section [ideas & suggestion > DCS feature request - voting](https://forum.storj.io/c/ideas-and-suggestions/dcs-feature-requests/36) That's the appropriate venue to propose it because people can vote it and it's very helpful for us to track them.

I'm closing the issue but if you have any other concern related with it, drop a comment here.
