### ISSUE TITLE
[Bug] Files created using Uplink are not visible in Storj GUI

### ISSUE THREAD

**Issue by sk-ismail** [storj/storj#4165]
### 1. I was trying to upload some pictures to my bucket in storj using Uplink cli. 
![Screenshot from 2021-07-26 11-14-55](https://user-images.githubusercontent.com/42185028/126939181-e5969640-1b88-4cef-a2a1-f65b2dec3175.png)
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
### 2. After uploading it using uplink cli is not visible in my storj GUI.

![Screenshot from 2021-07-26 11-16-13](https://user-images.githubusercontent.com/42185028/126939283-f8f7ac0c-29e7-44ef-baee-bc22731178b7.png)
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
### 3.whereas it is visible in uplink cli 

![Screenshot from 2021-07-26 11-15-28](https://user-images.githubusercontent.com/42185028/126939318-432306bb-ef83-4102-9711-6fbf3f885af9.png)

----Update----

when i was trying to delete that bucket using storj gui it was giving me warning that something is there in that bucket and it couldn't delete.
That means the files are there in that bucket but not visible in storj.

![Screenshot from 2021-07-26 11-34-26](https://user-images.githubusercontent.com/42185028/126940863-7c0da0ff-0c14-44d9-a6ba-a55fc6d2dcdc.png)

**Comment by ifraixedes** [comment]
Hello @sk-ismail,

Thank you for using Storj DCS.

That's expected behavior; when the objects are uploaded with one access grant, any other access grant, not derived from it, cannot list the objects of the former despite it has all the rights to access to the bucket.

That's what is happening. You used an access grant to upload the files and the web browser is using another access grant, hence the web browser doesn't list the objects because the access grant that's using is different.

If you want to list and access your objects from the browser then you have to use the web browser to upload them.

**Comment by sk-ismail** [comment]
yeah i tested it again by creating a new project and it was working fine and the files were visible in the GUI as well.

### I Faced another issue:-
while switching between the projects, we need to import our key as below but it is giving error:-
![Screenshot from 2021-07-26 19-06-03](https://user-images.githubusercontent.com/42185028/126998008-b9b7dbca-132f-4739-998c-7bc103097ecf.png)

Everytime I have to go inside the Config.yaml file and clear the access key and try it again with new key in order to run the above command.
![Screenshot from 2021-07-26 19-08-07](https://user-images.githubusercontent.com/42185028/126998361-8f48b3ed-7a70-49d8-af56-dfc7e14c4312.png)

**Comment by ifraixedes** [comment]
> yeah i tested it again by creating a new project and it was working fine and the files were visible in the GUI as well.

Brilliant!

> I Faced another issue:- ...

That's because the `import` command accepts an optional name for the access grant that's importing. When the name isn't provided it uses `default` and if the uplink configuration has already an access grant named `default` then it will reject it because it already exists.

Below you can see the help message of the `import` command

```
> uplink import -h                                                                                                                                                                                                                    
Imports an access into configuration. Configuration will be created if doesn't exists.

Usage:
  uplink import [NAME] (ACCESS | FILE) [flags]

Flags:
  -h, --help                               help for import

Global Flags:
      --advanced                         if used in with -h, print advanced flags help
      --config-dir string                main directory for uplink configuration (default "/home/user/.local/share/storj/uplink")
```

Hence, you should succeed in importing it if you pass a name that doesn't exist in the configuration file. For example `uplink import my-access '/home/ismail/keys/1stuser.key'`

**Comment by sk-ismail** [comment]
yeah i have done this and access to my new project was created. 
I am not able to access or create any new buckets in the new-project as the access is still in the old project though the the access key of the new project is added  in config.yaml file.
so,How to create buckets in new-projects?

**Comment by ifraixedes** [comment]
Every project has its own access grants, hence you have to create one or more access grants to a project and then use them for manipulating the data (create/delete buckets, upload/download/delete/list objects, etc.)

**Comment by iglesiasbrandon** [comment]
This issue is stale. This code path has been rigorously tested and is working as expected.
