### ISSUE TITLE
Make software user friendly like BTFS/Sia

### ISSUE THREAD

**Issue by jaffsys** [storj/storj#4204]
Connecting node seems biggest of problem. Node is offline even after trying all troubleshooting mentioned. Why can't storj use something similar to BTFS or Sia? Just click allocate and earn.

**Comment by grafael** [comment]
Hi, @jaffsys could you describe in detail the problem you are facing? Details like: Hardware, operational system, error logs, etc may help us to give you better directions.

**Comment by jaffsys** [comment]
Hi @grafael,
Tried all methods for troubleshooting node offline. Could not get the node online. Can't Storj use upnp or other methods to automatically get the node connected to the network?

**Comment by grafael** [comment]
We do not support UPnP. Please, try following the steps described here: https://docs.storj.io/node/  If you still have trouble setting your node please send us more error details.

**Comment by jaffsys** [comment]
I could not open the port as mentioned in the guide. I am not able to find a way to get host online

**Comment by ifraixedes** [comment]
If it's what @stefanbenten said, perhaps you have the choice to tell your ISP to sit your connection out of the Carrier NAT.

I know that some ISPs allow it because in 2 of my previous ISPs I had to ask for it.

By default, some ISPs put all the clients behind the Carrier NAT for avoiding IP v4 starvation. I guess that because most of the clients don't ask for being out, they are fine to move out some of the clients that they ask for.

**Comment by jaffsys** [comment]
I will try this with my ISP.
