### ISSUE TITLE
Footer for Storj DCS satellite page

### ISSUE THREAD

**Issue by nerdatwork** [storj/storj#4288]
Currently there is no footer and I would like to recommend a footer as shown below

![image](https://user-images.githubusercontent.com/15882196/142864179-fe0cfe7d-fbbc-4e56-8e03-83000b086138.png)

1. Storj = will lead to Storj.io homepage

2. Copyright = Showing the range `2014-2021` from when Storj was founded up to current year immediately conveys that Storj isn't new in the business. 

3. Community = Links to Storj DCS section of the forum not the SNO section

4. Support = This is very vital since there are situations where an error message asks user to contact support but no "clear way" to do so.

![image](https://user-images.githubusercontent.com/15882196/142865469-b241c0c7-5a06-4952-b40a-33a79348c1c9.png)

As it can be seen above the error message asks for `contact support` but there is no way to do so. Adding a hyperlink to `contact support` in the error message itself would also be a good idea. This link will autofill the subject too for increase in project limit.

**Comment by mobyvb** [comment]
I have created a ticket in the customer growth backlog to address the project limit error, which asks you to contact support.

I also added a new label to this issue, "Design/Marketing Suggestion" because of your footer idea. These types of design and marketing decisions are outside of the scope of the customer growth developer team.
