### ISSUE TITLE
[Objects browser] Create a bucket in empty project. Error "Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1"

### ISSUE THREAD

**Issue by stoweandi** [storj/storj#4370]
Also see comments in jira thread: https://storjlabs.atlassian.net/browse/USR-1922

**Comment by mobyvb** [comment]
I was able to reproduce the issue by adding the following line to my `/etc/hosts` file 
```
127.0.0.1 auth.us1.storjshare.io
```
Meaning a firewall could be blocking the authservice for this customer, preventing them from using the object browser

I will follow up shortly and respond to the customer about next debug steps

**Comment by stoweandi** [comment]
@heunland can you review the comment in the Jira ticket and let us know if that brings resolution to this support issue?
Thank you!

**Comment by mobyvb** [comment]
@NiaStorj I added story points, but I don't think there is anything actionable on the User Growth team for this task at the moment. We've established that this is due to Storj services being blocked by the users' internet providers, but I don't think there's anything that the UG team is able to do about this issue.
