### ISSUE TITLE
Uplinkng missing features

### ISSUE THREAD

**Issue by mniewrzal** [storj/storj#4377]
This is list of features that uplinkng is still missing comparing to old binary:
important
* error is always displaying stacktrace

less important
* while coping metadata cannot be set
* --debug.trace-out is not working
* `--parallelism-chunk-size Size    Controls the size of the chunks for parallelism (default 64000000)` "Size" as a flag type make not much sense for user

**Comment by zeebo** [comment]
- I prefer error stack traces, but I'm not an end user. Maybe we have a `--verbose` global option that controls if they are printed? this would be easy to implement.
- all of the --debug flags are not implemented. indeed, we don't even send metrics which makes it funny that we prompt for collection :smile:
- i can make a clingy change so that it at least prints `(default 64.00 MB)`. dunno what to do about the flag type, though, because that's the name of the type. the library has a `reflect.Type` value that it can use to figure out what to print.

**Comment by mniewrzal** [comment]
> * I prefer error stack traces, but I'm not an end user. Maybe we have a `--verbose` global option that controls if they are printed? this would be easy to implement.

For sure something to control that would be nice. Not sure yet if that should be `--verbose` or for example `--debug`

> all of the --debug flags are not implemented. indeed, we don't even send metrics which makes it funny that we prompt for collection

Yeah, my personal preference would be to remove all unimplemented flags until we will implement it. It may avoid some confusion. I think the question about sending metrics is fine, we are asking in advance ;) But do we want to bring back metric sending later?

> i can make a clingy change so that it at least prints (default 64.00 MB). dunno what to do about the flag type, though, because that's the name of the type. the library has a reflect.Type value that it can use to figure out what to print.

this is totaly nit for me. I wouldn't spend time on it atm. I put it here for tracking.
