### ISSUE TITLE
Set NodeSelectionConfig.SuspensionDQEnabled to true in Prod and tell forum

### ISSUE THREAD

**Issue by shaupt131** [storj/storj#4434]
this is for unknown audit suspensions

[Formerly DUR-85](https://storjlabs.atlassian.net/browse/DUR-85)

**Comment by mobyvb** [comment]
@iglesiasbrandon I did some digging and found when the flag was originally added: https://github.com/storj/storj/commit/8f60cfc4fb
And it looks like it has been disabled in prod ever since. I think we didn't enable it because there were certain errors that nodes returned during audit at the time that were bugs in the code, and not the fault of the node operator. So we did not want to disqualify nodes until we solved all of those "suspension error" bugs. The intention was to turn on suspension DQ once we fixed all of those bugs, but to be honest, I don't know if we ever got there, or where we are currently.

**Comment by iglesiasbrandon** [comment]
@kristaxox @jenlij @shaupt131 @mobyvb @littleskunk @thepaul we need to decide if this ticket is still valid. Does anyone have any insights on this? its a super old Jira ticket that never got worked on. It feels quite stale to me. i think we should consider closing it.

**Comment by thepaul** [comment]
We do still need to turn on SuspensionDQEnabled at some point. I feel like the community is aware by now that extended time in suspension will result in a DQ, so it may not require a full announcement in the forum, but at the very least we need to enable the flag before closing this ticket.

**Comment by shaupt131** [comment]
@thepaul is this issue still relevant?

**Comment by thepaul** [comment]
Yes, we still haven't enabled that flag. This is unrelated to GE.

**Comment by iglesiasbrandon** [comment]
it does not seem like we are going to be doing this. I am going to close this issue until it is. @thepaul please reopen if needed.
