### ISSUE TITLE
When an email already has an account, show this message on sign up form

### ISSUE THREAD

**Issue by stoweandi** [storj/storj#4733]
When a user goes to create an account with an email address that is already on that satellite I want them to receive a message on the signup form that informs them that they can't use that email address.

Thoughts:
- inform the user the email already exists "An account already exists with this email address."
- we could also suggest they reset their password
- we could also send an email that informs them there's an attempt to create an account with their email address and if this is them to show them the password reset link

**Comment by ifraixedes** [comment]
I know that most of the services will tell me that an account already exists if I try to create an account with an email that is already registered, however, I don't like it because people can find out who is registered.

I'd rather send a confirmation email (if there isn't any account created with the indicated email address) than the user has to click the link to continue with the registering process. This would avoid that somebody could find out if a specific email address is registered. The downside is that sending links in emails is a usual attack vector, so we should do our best for users to be able to identify legit Storj emails.

**Comment by liviolanda** [comment]
@ifraixedes let me know if the second option for "Sign up - email already exists" works as you think is best.
https://www.figma.com/file/Yzgkpah3gDUbVjaqEfJoke/Liv-Labs?node-id=2821%3A257971

**Comment by ifraixedes** [comment]
@liviolanda it's less obvious that the email is already used, however, if somebody has that goal, they will easily find that the message appears one an account with the indicated email exist and the result.

I think that the only option is that the user has to receive an email to follow the registration process.

**Comment by liviolanda** [comment]
Could we just change the message of the email then? 
Here is a suggestion that tells what was the error for the email owner, if somebody is trying to create an account with a registered email. 

https://www.figma.com/file/HlmasFJNHxs2lzGerq3WYH/?node-id=13329%3A117004

**Comment by NiaStorj** [comment]
no longer needed
