### ISSUE TITLE
Implementation of the payment API

### ISSUE THREAD

**Issue by shaupt131** [storj/storj#4787]
When a user deposits STORJ token into their account
I want the satellite user interface to pull information about the transition into the GUI
So that I can keep track of the transactions I have deposited into my account.

The purpose of this API endpoint is for the UI to b able to pull data about payments from the satellite. 

Backend for https://github.com/storj/storj/issues/4337

**Comment by iglesiasbrandon** [comment]
Discussed this item during sprint planning today (7/19). In order to support payments from multiple services such as storj scan, coinpayments.net,  and zksync or any others in the future we are going to update the payments API to pull payments associated to a specific user instead of a specific wallet address. This will allow us to show all of the payments the user has made in the GUI regardless of the way they did them. @rikysya @dlamarmorgan
