### ISSUE TITLE
Review Figma design for project welcome screen

### ISSUE THREAD

**Issue by littleskunk** [storj/storj#4793]
https://www.figma.com/file/Yzgkpah3gDUbVjaqEfJoke/?node-id=2466%3A229874

**Comment by nadimhq** [comment]
Project welcome screen after login looks clean, there is a lot of white space and some of the buttons have a lot of dropdown options maybe it is possible to break these dropdown options into separate buttons on the otherwise empty page especially for the first project page. Should bring more clarity to possible first time users, also forum link seems to be missing unless it is part of the go to docs dropdown (still could be a clarity issue).

Also once accounts reach three projects even though they are paid tier have to contact support to add another project. Should this be highlighted on the projects page?

Also what about projects with multiple users? Should the project page show the user number/ names on said project description? Should bring more clarity onto projects since at the moment only number of users can be seen on the manage projects page.
