### ISSUE TITLE
Move "billing" top level navigation item to "My Account" as a sub item

### ISSUE THREAD

**Issue by iglesiasbrandon** [storj/storj#4846]
AC:
- The billing navigation menu item is removed as a top-level item
- The billing navigation menu item is added under "My account" as a sub nav menu item

Link to Figma screen: 
@liviolanda

**Comment by VitaliiShpital** [comment]
I think @heunland should have some thoughts about it

**Comment by heunland** [comment]
Please do not remove Billing from the top level menu. We used to get tickets from customers unable to find the billing section because it was hidden, until it was placed on the top level menu where it is easy to find.
If you now hide it again all the way on the bottom in a submenu  of ¨My Account¨ we will again have confused customers filing unnecessary tickets. 
Please explain what is the reason for making it hard to find the billing section again now? Do we not want to make it easy for customers to find how to upgrade to Pro Account for example?

**Comment by mobyvb** [comment]
cc @liviolanda

**Comment by liviolanda** [comment]
We moved the Billing to under Account because [we are redesigning the multiple projects dashboard] and we needed to keep fewer links and added Billing as part of the dropdown in Account. (https://www.figma.com/file/HlmasFJNHxs2lzGerq3WYH/?node-id=14389%3A131874)

We used to have Billing under Settings in a topbar menu before, and when we redesigned we made it an "exposed" item in the navbar. Now, with the proposed change, we're suggesting Billing is related to Account, not to the Project. If we leave it as part of the Project menu, some users could understand they're seeing Billing by Project, and they're not. 

Also, Billing is an item that is usually under Account in digital products, so I strongly believe the users won't get as lost as they were when we had this item under Settings, because they are very familiar with this path.

We could also A/B test this change before pushing this update for 100% in prod @mobyvb @heunland

**Comment by stoweandi** [comment]
@heunland / @VitaliiShpital before, billing was hidden under the "Settings" drop down. In other products "Billing" is under "Account". This change is to move Billing to be like other products, being positioned under Account. It will also be a betterr UX for new All Project dashboard changes we are working on.

**Comment by liviolanda** [comment]
**Design** 
https://www.figma.com/file/HlmasFJNHxs2lzGerq3WYH/?node-id=15108%3A108760


**Behavior**
Show notification first-time user access dashboard after we made the change.

Notifications links:
See Billing -> takes to the Billing page
X -> closes notification

If the user clicks on “My Account” the notification disappears.

**Comment by stoweandi** [comment]
Note: do not deploy without the notification ticket being ready: https://github.com/storj/storj/issues/4962

**Comment by xaresys** [comment]
deployed in v1.63.1
https://github.com/storj/storj/commit/ffd35ecfdcb4fe5d6744c571f8a733426dafd717
