### ISSUE TITLE
Satellite email for: Trying to create a new account with already verified credentials

### ISSUE THREAD

**Issue by stoweandi** [storj/storj#4912]
When a user goes to create an account with an email already verified on a selected satellite, I want the satellite to send the user an email asking them if they are trying to sign in, so that they are notified that they already have an account and are given the option to reset their password if needed.

AC:
- when a user tries to create an account with already verified credentials, we do not want to expose in the signup form that the credentials were already used
- the user receives an email from the satellite reminding them they may already have an account
- this email also notifies the user if an attacker is trying to gain access to their account 

Figma: https://www.figma.com/file/HlmasFJNHxs2lzGerq3WYH/Satellite-GUI-Public?node-id=15007%3A107872

**Comment by mobyvb** [comment]
Text from another ticket before I realized it was a duplicate:

Inside Register in satellite/console/consoleweb/consoleapi/auth.go, if the email being registered already exists in the users table, the ForgotPasswordEmail is sent. This is confusing to users who already have an account associated with their email, but didn't know or forgot. They think they should get a verification email, but get a reset password email instead.

Job Story:
When I try to register with an email that already has a verified account,
I want to receive an email notifying me that this account already exists, with information about how to login or reset my password,
so that I am not confused by a "reset password" email after filling out the signup form

Pain point: Customers confused by "reset password" email when they were trying to create a new account

AC:
Instead of sending the forgot password email if the account already exists on register, send a new email similar to the others in web/satellite/static/emails with the following text (there is a figma design so I won't include the text here):
...
