### ISSUE TITLE
Add a batch insert for the billing table

### ISSUE THREAD

**Issue by iglesiasbrandon** [storj/storj#4916]
When the chore runs I want to add any storj scan transactions into any payments tables in stores transactions specific to coinpayments but we need to add those payments to the billing table so that the invoice charges are stored in the billing table

**Comment by jenlij** [comment]
This turned out to be a larger issue because there was a lot of discussion about what happens when a payment cannot be inserted into the table. We ended up not using batching and relying on a created_at timestamp and inserting the payments one at a time to make sure the order of payments is maintained.
