### ISSUE TITLE
Fix Billing table batch insert

### ISSUE THREAD

**Issue by iglesiasbrandon** [storj/storj#5011]
We need to resolve the concern in the comment here: https://review.dev.storj.io/c/storj/storj/+/7787/comments/4025a772_8c69ce9e

Acceptance Criteria: 
- TBD

**Comment by iglesiasbrandon** [comment]
@thepaul we need your input on this: 

Open Questions: 
- How do we prevent the user's balance from becoming negative? we thought we could do this with the extra table
- in a batch insert, there are two problems with this approach; the transactions may not be in order and the actual update of the billing balance table would even really prevent the balance from going negative. 

Please see the conversation in the ticket for more context.

**Comment by thepaul** [comment]
@iglesiasbrandon I think I am still missing too much context. I have two conflicting impressions of the way things stand. I think the situation is described by one of these, but I don't know which:

1. Statements within a batch might execute in any order, so there might be some orderings where a user's balance goes temporarily 'negative' in the middle of a batch. But all user balances must be >0 at the end of the batch.
2. Whole batches might execute in any order, that is, we have batch B1 and batch B2 and we can't know which one will execute first. And, depending on which order they run, some user balances might be left negative at the end of the batch.

If it's number 1, then that's fine, we can sum up amounts for each affected user and update user balances only once per batch.

But from the changeset comments, it looks like the problem is number 2, and a solution for that would be more complicated.

**Comment by shaupt131** [comment]
Design no longer calls for batching of debits.  Issue can be closed.
