### ISSUE TITLE
Satellite UI: Don't download entire object during preview

### ISSUE THREAD

**Issue by stoweandi** [storj/storj#5025]
From Vitalii
> so there is another problem with object preview. I remember some thread where Brandon reported that some heavy videos are loaded very slowly. That’s an issue we have to solve somehow. Right now basically we download the whole object preview and set download blob as a source of media html tag. We do that because we reworked our preview flow to be done by signed requests. I have to investigate how we can set media tag source to have signed request URL (don’t know what’s the correct name of that) instead of downloading the whole object first

This is the change that resulted in this issue: https://review.dev.storj.io/c/storj/storj/+/6731

AC: 
* revert the changes from PR /6731 linked above.

**Comment by VitaliiShpital** [comment]
This issue is really problematic to solve. We can't set custom headers (`signature` in our case) for html media tags (<img>, <video> etc.) source. We implemented aws request signature solution to solve some high severity issue to add more caching to file browser. So to get object preview by signed request we have to download entire object first and then set downloaded blob to html tag source.

Here are some links
https://alphahydrae.com/2021/02/how-to-display-an-image-protected-by-header-based-authentication/
https://programmer.ink/think/how-to-add-a-custom-header-to-requests-in-the-img-tag.html
https://stackoverflow.com/questions/27000152/set-custom-header-for-the-request-made-from-img-tag

**Comment by mobyvb** [comment]
@iglesiasbrandon I need to talk to you about what the next steps here are

**Comment by iglesiasbrandon** [comment]
Discussing this with @mobyvb , 

If we are able to revert our current state back to what we had previously (where the object was not cached in the case of a refresh) 

Action Items: 
- revert back to the previous functionality
    - as long as the previous functionality does NOT download the entire object automatically when the object details modal window is opened
- discuss/ investigate if it's possible to have a streaming preview with caching 
- discuss if we should add functionality to disable preview on a user level for the object browser. 

The current experience is worse than what we previously had because we are downloading the entire object before the user is able to see a preview or play the object. 

Updating the Acceptance Criteria of this ticket as well.
