### ISSUE TITLE
Write testplan for scaling audit worker

### ISSUE THREAD

**Issue by littleskunk** [storj/storj#5043]
https://review.dev.storj.io/c/storj/storj/+/8041

**Comment by nadimhq** [comment]
<google-sheets-html-origin><style type="text/css"></style>

Test Scenario | Test Case | Description | Comments
-- | -- | -- | --
Audit Scaling General | Positive/Negative | Test for when node joins network, nodes must past a certain number of audits and if the node passes a certain number of audits then the node is fully vetted else it is not |  
  | Vetted Status Check | A node should only be considered vetted if it recives a total of 100 audits, so nodes under said number should not be vetted && The number of audits a new node requires to be vetted should never fall below aforementioned total, so quality of nodes on network doesn't decrease and thus negatively affect network durability |  
  | Audit Scaling | If new nodes are onboarded then there shouldn't be limited audit scaling because of satellites with the introduction of said measure for audit scaling |  
  | Unvetted Nodes | New nodes should follow a set percentage of data from new uploads (5%) |  
  | Vetting Times | Vetting time on average now should (according to metrics) should be 1 month to scale audit workers |  
  | Avoiding DQ 1 | If a node tries to get another pending audit because there are multiple audit workers working on the same node it should be doable, otherwise there can be a situation where the node can continously bypass DQ | explained in blueprint, snippet from forum (https://forum.storj.io/t/design-draft-refactor-pending-audits-to-allow-for-increasing-the-number-of-audit-workers/19189/2)
  | Avoiding DQ 2 | In the aforementioned case, if there is a successful audit it should remove only the corresponding entry and not all pending audits |  
  | Contained Flag | As long as a node has pending audits then the node should have a 'contained' flag set to true, and if there are no pending audits then vice versa NOT contained |  
  | Pending Audits Reverfication | With the new solution, nodes should not be reverified with pending audits and skipped in regular audits, there should be a separate process that iterates over the data from the pending audits table and spins up workers to audit those particular pieces ALL IN ALL Regular audits should be able to insert an entry into the pending audits table but it should not be able to be used to reverify AND there should be separate workers for regular audits & pending audits |  
  | Audit outcome | During an audit outcome if a node is audited with no problem then audit count should increase by 1, if it needs to reverify because of ex. time out, then it should be placed into pending audits table by the audit worker |  
  | Reverify outcome | When a pending audit worker selects an entry from the pending audits table if it is audited with no problem then audit count should increase by 1, however if there is an issue and the process times out then the reverify count will be incremented, and this pending audit should in the future get selected again by a pending audit worker until audit count increases by 1 |  
  | Next reverification | Depending on the outcome of said pending audit (ex. selected 1st time from pending audits table or has existing reverification count), then for the former, it should just wait for the next available audit worker or be selected at random, while for the latter it should wait for an x amount of time and a field for attempted_at timestamp should be created |  
  | Failure Prevention | The retry interval mentioned previously should not lead to an increase of artificial spreading of failures and be exploited to avoid disqualification | explained in the blueprint, with more spread-out failures, node operators would be able to abuse this f.e even if their nodes suffered significant data loss, b/c of spread outfailures this would be spread out and nodes that should have been DQ would scrape by
  | Verify Updates (Unit Tests etc.) | F.E reverifier, audit setup...new pending audits should be inserted directly into db | explained in blueprint, lines 82-147

**Comment by littleskunk** [comment]
I have a few question

There is a conflict between `Avoiding DQ 1` and `Avoiding DQ 2`. The first test is saying it should not be doable but the second test claims that it should be doable to add multiple pieces to the reverifcation queue. So which one is correct? It could be the wording of the first test case. I believe a node can miss 2 concurrent audits and we should add both to the reverifcation queue. We should force the node to reverify both audits and not allow it to bypass one of them.

How does `Next reverification` work? Let's say a node goes offline and we add 2 audits to the reverification queue. The node is still offline. I would expect that we don't try any reverifcation before the node comes back online?
Let's say the node does come back online for a short moment. If I understand the test plan correctly we will reverify 1 or maybe 2 pieces from the first round but since the audit job and reverification are different jobs now the node might also get 2 new audits. Node goes offline again. This means the reverifcation queue will not contain 4 pieces. Next time the node comes back online in which order do we process them? Do we want to add some kind of timelock? Wait 5 minutes before trying again? That would have the advantage that a node with a temporäry IOWait issue might be able to recover within 15 Minutes and continue just fine or fail the internal filesystem check and shut down that way. Without a timelock I am worried that a node might get DQed before the filesystem check has a chance to kick in. On the other hand it would be great if we could always reverify the piece with the highest reverification count. So reverify the piece first that has the highest chance to apply a penalty. If we do random order here or if we order by timestamp a big node with a permanent IOWait issue could add new pieces to the reverifcation queue faster than we can process them. We wouldn't DQ this node for a long time.

**Comment by jenlij** [comment]
Avoiding DQ 2 is correct. Avoiding DQ1 is worded incorrectly - we do want to be able to add multiple pending audits per node.

**Comment by jenlij** [comment]
Reverification audits only get added if a node is ONLINE but also times out its audit. If it is offline, it does not get a new pending audit to be reverified.

**Comment by thepaul** [comment]
A few notes:

On "Pending Audits Reverification", it says `nodes should not be reverified with pending audits and skipped in regular audits`. I'm not sure if this is talking about a specific scenario, but when a node is contained, it _should_ be reverified with pending audits and it _should_ be skipped in regular audits. Not sure if this is a typo or a mistake or if I'm just confused.

I don't quite understand the description for "Next reverification". But if another reverification needs to be done, it should happen as soon as `audit.reverification_retry_interval` time has passed AND a reverification worker is available.

**Comment by littleskunk** [comment]
Ok in that case I think we can get the test plan over the finish line. I don't have additional questions.

**Comment by nadimhq** [comment]
https://github.com/storj/storj/blob/main/docs/testplan/scaling-audit-worker.md

already merged, ticket can be closed
