### ISSUE TITLE
Update how we send token payment to stripe to mark an invoice as paid

### ISSUE THREAD

**Issue by iglesiasbrandon** [storj/storj#5121]

**Comment by dlamarmorgan** [comment]
Some options that Brandon and I have brainstormed.
1) We mark the invoice as paid if the user is paying with storj tokens. This is the simplest approach, but has the downside of being complicated if the user is paying only part of their invoice amount with tokens. It's unclear how we would support this option.

2) Add a balance to the users stripe account after the invoice is finalized to pay all, or a portion of the invoice. This option is similar to how coinpayments worked previously, with the difference being we are keeping the "unspent balance" on the satellite instead of within stripe. We would only send funds from this balance on the satellite to the stripe account as needed to pay an invoice.

3) Explore using the stripe API to send "out of band" payments to stripe.
```
paid_out_of_band
optional
Boolean representing whether an invoice is paid outside of Stripe. This will result in no charge being made. Defaults to false.
```
It is unclear how this option differs from option 1, but it's possible that it allows for paying a partial amount of the invoice that the first option wouldn't support easily. More research would be required to explore the limitations of this option.

**Comment by dlamarmorgan** [comment]
4th option perhaps?
Do we pay for Stripe support? Maybe we can ask their engineering team what they recommend would be the best approach for this problem. I'm sure they've heard the question before. If it's an easy thing to get their recommendation, it would probably be good to hear it.

**Comment by jenlij** [comment]
Waiting to hear back from finance dept for their opinion on which route to take.

**Comment by dorrie55** [comment]
@dlamarmorgan I strongly support your recommendation to reach out to stripe support for their recommendation.

@jenlij - Finance is agnostic on which option is chosen and is more interested in the outcome as follows:
1. an invoice can be "paid" in STORJ token the same way that an invoice is "paid via cc" regarding application of payment to invoice and payment audit trail being available
2. An invoice can be partially paid with remaining STORJ token and continue to show a balance due and then a credit card will be applied by stripe for the remaining balance.  First STORJ token then credit card for payment sequence
3. The ability for FInance to run a report showing on a per invoice and/or per customer basis the amount of STORJ token applied to invoice balances as payment
4. Also need to account for and track the 10% bonus amount.

The above is not different than the specifications I've outlined previously and hopefully helpful

**Comment by dlamarmorgan** [comment]
Another late breaking option.. Credit Notes.
https://stripe.com/docs/invoicing/dashboard/credit-notes
https://stripe.com/docs/api/credit_notes

Credit notes have the advantage of allowing us to customize the resultant PDF invoice with a unique item and description, as opposed to a general "balance applied" entry as is the case with stripe balance adjustments. This is useful in the case of having more than one payment type outside of stripe, and wanting to differentiate them on the invoice. Credit notes allow us to handle this easily it seems.

@Dorrie how does finance feel about the credit note option? I'm not sure what it would look like on your reporting, but here is a PDF that shows an invoice with both an "applied balance" from a users stripe balance as well as a credit note to highlight the differences.

[Invoice-F445BE64-0001 (4).pdf](https://github.com/storj/storj/files/9536795/Invoice-F445BE64-0001.4.pdf)

**Comment by dorrie55** [comment]
@iglesiasbrandon @jenlij @dlamarmorgan - I much prefer the credit note option since folks will know what it is and also likely finance could generate a better report on credit notes then on an applied balance.

**Comment by dlamarmorgan** [comment]
https://review.dev.storj.io/c/storj/storj/+/8420
