### ISSUE TITLE
Write testplan for linksharing TLS support

### ISSUE THREAD

**Issue by littleskunk** [storj/storj#5125]
https://review.dev.storj.io/c/storj/gateway-mt/+/7822/6/docs/blueprints/tls-custom-domains.md
https://docs.google.com/document/d/1dXTTMWCjs85xOcVo2c3UEil6LxwbBPCBUKKAGcxyxvw/edit#heading=h.5wzfc3vn57jc

**Comment by nadimhq** [comment]
<html>
<body>
<google-sheets-html-origin><style type="text/css"></style>

General | Certificate Generation | Storj should generate certificates on behalf of users if users have a way to prove ownership of domain to generate said certificate
-- | -- | --
  | Custom Domain URL | Linksharing URLs generated w/ custom domain should also have an additional URL that contains said custom domain
  | uplink CLI share request | Customer should be able to make a share request with uplink CLI and be able to update their DNS info w/ output from uplink cli
  | Share Access 1 | When a share is accessed, linksharing should load the certificate matching the SNI and should attempt to connect said hostname at the start of the handshake
  | Share Access 2 | Once trying to connect to hostname, linksharing should check for certificate in the cache first and then if it is not there it will check the store
  | Valid/Invalid Handshake | If the certificate doesn't exist in the store and the CNAME is valid, then there should be a request for a certificate store domain-lock else this is an invalid handshake and handshake fails/request is dropped
  | Successful domain-lock | If the domain-lock succeeds, then the certificate should be requested and the certificate validation process should run afterwards with the new certificate being added to the store
  | Multiple Request on domain-lock | When requesting a certificate, additional requests made to the instance holding the lock can be held while the certificate is issued
Certificates | Storing | Certificates should only be stored in one private Storj controlled DCS bucket and said bucket should share certificates and other TLS resources needed for the challenges between all linksharing instances
  | On-access Renewal | If a certificate expires in less than 30 days and it is accessed, it should then be renewed & if it doesnt expire in less than 30 days it should not be renewed on access
  | Expired Certificate | If a certificate expires before it is accessed or after is it accessed for a set time (30 days), then it should be reissued on next access since it will be in process for garbage collection


</body>
</html>

**Comment by ihaid** [comment]
Looks good to me 👍

**Comment by halkyon** [comment]
> Only pro accounts should be able to use Linksharing TLS

This can be removed for now, or marked as out of scope. Edge team decided in the recent sprint planning to not do this.

**Comment by shaupt131** [comment]
@halkyon @nadimhq I believe we need to add the "Only pro accounts should be able to use Linksharing TLS" back into the test plan as it is now a requirement (see https://github.com/storj/gateway-mt/issues/241) CC: @NiaStorj

**Comment by NiaStorj** [comment]
@littleskunk are you able to add back the paid tier/pro account to the test plan?  

Lastly, Are you able to give any insight into how long it will take QA to execute the test plan once all dev work has been deployed to a QA branch?

**Comment by nadimhq** [comment]
@littleskunk added the case back

**Comment by NiaStorj** [comment]
@nadimhq thank you! Do you have an estimate on how long it will take to test this feature?

**Comment by nadimhq** [comment]
@NiaStorj I'm not sure but I think @littleskunk may have a proper estimate

**Comment by littleskunk** [comment]
@NiaStorj the QA team is too small to automate all of these tests. The idea is that we deliever the test plan to the developer team and they implement these tests side by side with the new feature. By the time the feature is ready for the deployment on the QA satellite the QA team hopefully only reviews the existing tests. Ideally the test automation covers everything we hand in mind with the original test plan so that we can just deploy it in production without having to run a single manual test.

Do you want to know how long the QA team would need to review existing automated tests? That usually takes just a few days.
