### ISSUE TITLE
Auto finalize invoices that are $0.00 each month after they are generated.  

### ISSUE THREAD

**Issue by iglesiasbrandon** [storj/storj#5155]
**Describe the feature or problem you'd like to solve**
The problem we are trying to solve is the time it takes to create and finalize the invoices for our customers each month. The amount of time it takes to run the finalize invoice command is linear to the number of customers we have. The purpose of this ticket reduces the amount of time it takes to finalize invoices that are $0.00 by doing that automatically. This will reduce the number of API calls we must make to stripe for invoices we want to finalize with us manually running the finalize command.

**Propose a Solution**
- Auto finalize invoices where the amount due is 0.00. 
- This can be done using the automatic advancement functionality on stripe. 
- https://stripe.com/docs/invoicing/integration/automatic-advancement-collection

**Acceptance Criteria:**
- Invoices that are generated that have an amount due equal to 0.00 are automatically finalized. 
- Any invoice that is 0.00 or greater must NOT automatically be finalized.

**Comment by xaresys** [comment]
@iglesiasbrandon When an invoice has been marked for automatic advancement, there is a [1-hour delay](https://stripe.com/docs/invoicing/integration/automatic-advancement-collection#toggle-auto-advance) before it is finalized. Because of this, it is possible that the invoice would be finalized sooner had we manually performed finalization. With this in mind, is this ticket still relevant?

**Comment by stefanbenten** [comment]
Manual performend finalization is currently just setting the auto advance flag. That would mean this ticket should still be relevant.

**Comment by xaresys** [comment]
Deployed in v1.66
storj/storj@3d6c3e3
