### ISSUE TITLE
Improve testplan for Token Payment Processor

### ISSUE THREAD

**Issue by littleskunk** [storj/storj#5179]
The first version of the test plan has worked very well. We have been able to prevent a few bugs with that test plan: https://github.com/storj/storj/pull/4672

Fill out some more details with the new implementation details we have now.
https://storj.slack.com/archives/CSURA8VJP/p1661349919520789
Invoice generation order of items. coupons first, storj balance next and credit card last.
Show a test invoice to our accounting team and ask them if this invoice looks good. Ask them if the storj balance + 10% bonus can be added to stipe or if that messes up something. Are the reports for the accounting team correct?

**Comment by nadimhq** [comment]
Here are some additional tests taken from discussion surrounding new implementation details

<html>
<body>
<google-sheets-html-origin><style type="text/css"></style>

Test Case | Description | Comments
-- | -- | --
Two Transactions | If there is a pending transaction with less than the number of required confirmations and then there is a reorg and said transaction gets overridden with a longer chain, the old pending transaction should then get removed |  
Stale Pending Transactions | Pending transactions that have less than the number of required confirmations and have been stale for a set time should be deleted from the Satellite DB and not stored again |  
Pending Transactions | Same as above case, except it will be again stored in DB since all pending transactions are wiped from the DB regardless if they are stale or not (in this case its not stale, just pending and waiting for the minimum # of confirmations) |  
Required Block Confirmations | Transactions should have their required blocks for confirmation high enough so that even if there is a reorg with a pending transaction that contains f.e two chains same length in parallel, there shouldn't be an issue |  
Timestamp Issue | It should not be possible for two transactions on a block to share the same timestamp, however If there are two deposits with the same amount to the same address in the same block, then it would mean that they have the same timestamp and the only difference would be the transaction hash because of the different nonce (this is an issue with our current design) | Current Design, according to Damein design will be changed so timestamp will not be relied on
Rescan | Rescan should always start from the last fully confirmed block f.e in a reorg, so rescan should start at the height of said block |  
Invoice Generation | When an invoice is generated and "paid", coupons should be used first, followed by storj balance and then lastly credit card | This invoice should be shown to our accounting team and they should be asked if said invoice looks correct


</body>
</html>

**Comment by littleskunk** [comment]
These tests have been included in the original test plan. The test plan was merged.
