### ISSUE TITLE
Decrease order submission time for nodes to 12 hours instead of 48 hours. 

### ISSUE THREAD

**Issue by iglesiasbrandon** [storj/storj#5202]
Update this config value to be 12 hours instead of 48 hours. 

The reason we want to do this is so that we can run the customer invoice cycle earlier in the month. 

https://github.com/storj/storj/blob/929642b675e40ccffbe0b0d16a73384a0388cfeb/scripts/testdata/satellite-config.yaml.lock#L640

Acceptance Criteria: 
- update # orders.expiration to 12h0m0s

**Comment by iglesiasbrandon** [comment]
The person who picks up this ticket should look at some graphs to ensure that the majority of nodes to actually submit orders back to the satellite within 12 hours.

**Comment by profclems** [comment]
As discussed here https://storj.slack.com/archives/C047KSGPPQ8/p1668417729140959, we don't have much data to verify hat the majority of nodes to actually submit orders back to the satellite within 12 hours. The assumption is that since storage nodes should be online 60% to avoid suspension, the majority of the time they will submit orders in time. The options now consider 24h instead of 12h. At least that should be enough time to get a node back online to submit an order in time.

**Comment by mniewrzal** [comment]
https://review.dev.storj.io/c/storj/storj/+/8908
