### ISSUE TITLE
Define observer interface for sharded loop

### ISSUE THREAD

**Issue by mniewrzal** [storj/storj#5239]
We need a new observer interface for shared loop.

Acceptance Criteria:
* should work with multiple threads, implementer shouldn't be concerned with thread safety, naive implementation should be thread safe
* should provide ability to process inline and remote segment
* should provide ability to finalize processing (e.g. method at the end of inner loop)

**Comment by Erikvv** [comment]
The problem with the interface in https://github.com/storj/storj/issues/5223 is that it pushes synchronization problems to the implementation. 

```
type Observer interface {
	LoopStarted(context.Context, LoopStartInfo) error
	RemoteSegment(context.Context, *Segment) error
	InlineSegment(context.Context, *Segment) error
        LoopEnded(context.Context, LoopEndInfo) error
}
```

I was thinking something like below. The service will ask the `Observer` to create multiple `RangedObserver` instances which will process the segments. It will give also an opportunity to pass aggregated data back to the `Observer`, taking care that no such function is called concurrently.

```
type Observer interface {
    LoopStarted(context.Context, LoopStartInfo) error
    CreateRangedObserver(context.Context) (RangedObserver, error)
    RangeEnded(context.Context, RangedObserver)
    LoopEnded(context.Context, LoopEndInfo) error
}

type RangedObserver interface {
    RangeStarted(context.Context, LoopStartInfo) error
    RemoteSegment(context.Context, *Segment) error
    InlineSegment(context.Context, *Segment) error
    RangeEnded(context.Context) error
}

```

My golang-fu is not so strong so I should make a PoC implementation.

**Comment by elek** [comment]
> The problem with the interface in https://github.com/storj/storj/issues/5223 is that it pushes synchronization problems to the implementation.

Can you please help me to understand the problem better?

Based on my understand there will be multiple instances of the implementation of this interface (let's say 4), and each of them will be called by new segments one by one (but only 1/4 of the full segment space).

If I understand well, there won't be any concurrent call on the same interface. 

I like the simplicity of the original `Observer` interface, but it's not clear what is `LoopStartInfo`. Is it information about the full loop, or the range loop?

**Comment by Erikvv** [comment]
> Can you please help me to understand the problem better?

When you have a simple implementation like this:

```
class SegmentCounterObserver {
    count int = 0
    
    RemoteSegment(context.Context, *Segment) {
        count++
    }
}
```

When this observer is called by two threads, there is a race condition and the count will be wrong.

> If I understand well, there won't be any concurrent call on the same interface.

This is true for some observers like repair. But not for others like bloom filters, audit collector, tally.

> I like the simplicity of the original Observer interface, but it's not clear what is LoopStartInfo. Is it information about the full loop, or the range loop?

This currently only contains the start time of the full loop and is only used for bloom filters. We do intend to start the ranges all at the same time. So it won't be for example 4 ranges with 2 workers, it will be the same number of ranges as workers.

**Comment by Erikvv** [comment]
Asked Egon for feedback because he's experimented with concurrency primitives.

**Comment by Erikvv** [comment]
> Do we have stats how much overhead there is for a particular observer?

We have some stats on this at https://chronograf.datasci.storj.io/sources/3/dashboards/82?tempVars%5Bapplication%5D=satelliteproduction-storj&tempVars%5Binstance%5D=US1&lower=now%28%29%20-%2030d#

It seems 70% of the loop is observer time and 30% loop overhead. 

> Processing should happen on batches of segments rather than one at a time. (e.g. 1024 segments (or more) at a time)

We fetch batches of 2500 from cockroach but we dispatch them to observers 1-by-1. Do you also mean to change the observer signature?

from

```
RemoteSegment(context.Context, *Segment) error
```

to

```
RemoteSegment(context.Context, *[]Segment) error
```

I don't think this will make a significant difference by itself. It may open some optimization opportunities by changing underlying services to support batches. But this is somewhat out of scope of this change and also adds complexity. 

> 2. If we want true concurrency we want to have independent observers that will be combined at the end rather than aggregating all the results into the same observer.
> 
> If we use batch processing, then 2. is achievable without needing to implement "separate observers" per se, but rather you calculate the stats from those 1k segments and then merge the results into the main observer. Such observers then be safely run concurrently.

I suppose we can merge my two interfaces into one:

```
type Observer interface {
    LoopStarted(context.Context, LoopStartInfo) error
    LoopEnded(context.Context, LoopEndInfo) error
    RemoteSegment(context.Context, *Segment) error
    InlineSegment(context.Context, *Segment) error

    // duplicate the observer to start another batch
    Spawn(context.Context) (Observer, error) Observer
    // merge state of different batches
    Combine(context.Context, Observer) error
    // opportunity to release resources
    Close(context.Context) error
}
```

The semantics seem more complex to me. I prefer the 2-interface solution. But I acknowledge the 2 interfaces probably have duplicate or even identical state.

**Comment by egonelbre** [comment]
> It seems 70% of the loop is observer time and 30% loop overhead. The fastest observer takes 5 minutes, the slowest (repair) 2 hours.

What's the cost in ns of a single call to RemoteSegment or InlineSegment?

> I don't think this will make a significant performance difference by itself. It may open some optimization opportunities by changing underlying services to support batches. But this is somewhat out of scope of this change and also adds complexity.

The point here is that it will allow to make observers concurrent without needing to implement Spawn and Combine.

**Comment by Erikvv** [comment]
🙂 I will keep an open mind, I really want to get to a good solution.

> What's the cost in ns of a single call to RemoteSegment or InlineSegment?

I suppose you are worried because it is a virtual function call which inherently comes with some overhead?

I think I can deduce that it is negligible: The fastest observer on US1 is ~5 minutes out of ~8 hours. It is [not a trivial implementation](https://github.com/storj/storj/blob/68fe26ebe56f874281caf89eefbbb0facc31e431/satellite/metrics/counter.go#L52). It processes 350M segments. 5m / 350M = 850ns per segment.

If we want to measure more accurately we can attach NullObserver.

I do see that the loop does 2(!) calls to get the system time per Segment. 1 of these is prolly counted in the 850ns and the other in the 30% overhead (most of the 30% will be database ofc). Maybe it would be a bigger win to optimize this?

I did some benchmarking of the solutions below with 25000 segments. I tried to trick it so it doesn't devirtualize.

```go
type SingleObserver interface {
	Process(*Segment)
}

type NullSingleObserver struct {
}

func (n NullSingleObserver) Process(s *Segment) {
}

func observeSingle(observer SingleObserver, segments []Segment) time.Duration {
    start := time.Now()
    for _, s := range segments {
        observer.Process(&s)
    }
    return time.Since(start)
}
```

2.5 ns/segment

```go
func observeSingleWithTime(observer SingleObserver, segments []Segment) (total time.Duration, inner time.Duration) {
	start := time.Now()

	var duration time.Duration = 0
	for _, s := range segments {
		start := time.Now()
		observer.Process(&s)
		duration = duration + time.Since(start)
	}

	return time.Since(start), duration
}
```

1100 ns/segment inner loop (so this is slower than the counter observer in prod)
3300 ns/segment outer loop 

```
type MultiObserver interface {
	Process([]Segment)
}

type NullMultiObserver struct {
	count int
}

func (n NullMultiObserver) Process(segments []Segment) {
	for _, s := range segments {
		// call a non-virtual function so the comparison is kinda fair
		n.Add(&s)
	}
}

func (n NullMultiObserver) Add(segment *Segment) {
	// do an op so the optimizer doesn't elide this function
	n.count += segment.a
}
```

0.24 ns/segment

Conclusion about []Segment vs *Segment: the difference is 2.25 ns/segment. For 350M segments this is 100ms per observer. Optimization isn't worth it.

Conclusion about timers: in my benchmark this takes over 3 ms/segment. For 350M segments this is 18 minutes per observer. We should optimize this.

> The point here is that it will allow to make observers concurrent without needing to implement Spawn and Combine.

I don't understand this. If I have an observer like this:

```
class Observer {
    count: int

    Observe(segments []Segment) error {
        for _, s := segments {
            count++;
        }
    }
}
```

How do I make it threadsafe? Can you please provide a pseudo-code interface with implementation of a counter?

**Comment by egonelbre** [comment]
> I don't understand this. If I have an observer like this: ...

```
type Observer struct {
    mu sync.Mutex
    totalSegmentSize int64
}

func (obs *Observer) Segments(segments []Segment) error {
    partial := 0
    for _, seg := range segments {
        partial += seg.Size
    }

    obs.mu.Lock()
    defer obs.mu.Unlock()
    obs.totalSegmentSize += partial
}
```

**Comment by mniewrzal** [comment]
I like idea of having multiple segments in method signature:
```go
func (collector *Collector) RemoteSegments(ctx context.Context, segments []*segmentloop.Segment) error  
```
I'm now sure if doing synchronization internally won't be more complex at some point as in some cases we need shared state for most of time and putting this behind mutex might slow down things. Audit example where I would expect that whole piece processing would be behind mutex.
```go
func (collector *Collector) RemoteSegment(ctx context.Context, segment *segmentloop.Segment) error {
	for _, piece := range segment.Pieces {
		res, ok := collector.Reservoirs[piece.StorageNode]
		if !ok {
			res = NewReservoir(collector.slotCount)
			collector.Reservoirs[piece.StorageNode] = res
		}
		res.Sample(collector.rand, segment)
	}
	return nil
}
```

**Comment by egonelbre** [comment]
The goal is to avoid fine-grained synchronization when implementing the observer funcs. In the reservoirs case, there should be a way to calculate the "partial" result and then merge it back into the whole. So, you wouldn't have such a mutex that's being hammered during processing of the segments. This of course will require some rethinking how some of the observers work.

**Comment by Erikvv** [comment]
I'm writing two proof-of-concepts with the "2-interface solution" and the "multiple segments solution" at https://gitlab.com/erikvv/observer-interface

> I'm now sure if doing synchronization internally won't be more complex at some point as in some cases we need shared state for most of time and putting this behind mutex might slow down things. Audit example where I would expect that whole piece processing would be behind mutex.

I'll check this example, if we can merge the state somehow then we may not need a memory barrier per segment.

**Comment by Erikvv** [comment]
I've completed both PoCs at https://gitlab.com/erikvv/observer-interface. I can't say implementing it has swayed my opinion strongly either way.

Egons idea has less code, but it does push synchronization concerns to the observer, use a mutex in the observer. 
My design has a bit more code but does not use synchronization primitives anywhere (only storj.io/common/errs2.Group which both implementations use once to fire up the 16 workers).

All-in-all they're more similar than they are different.

**Comment by egonelbre** [comment]
@Erikvv so looking over the implementations. I would recommend running some of the observers concurrently, because I don't think they take different amount of time. e.g. a simple "metrics counting" is going to be much faster than repair. So you would want to run parallel "simple observers" and "slow observers". Trying to keep parallelizing on segments themselves is going to eventually hit bandwidth bottleneck.

Similarly the `SegmentProvider` should reuse the slices rather than reallocating.

> I haven't benchmarked but I don't expect a significant performance difference.

Here's a run doing 10k segments and 10k batches, with the allocation optimizations. I also updated the `Segment` to contain some data and rewrote the value in `GetBatch`.

```
observer-interface>go run ./pocsingle
pocsingle
3.4884786s

observer-interface>go run ./pocpair
pocpair
6.7511295s
```

**Comment by egonelbre** [comment]
Final design based on meeting:

```
type Observer interface {
	Start(context.Context, time.Time, metabase.NodeAliasMap) error

	Fork(context.Context) (Partial, error)
	Join(context.Context, Partial) error

	Finish(context.Context) error
}

type Partial interface {
	Process(context.Context, []Segment) error
}
```

**Comment by azdagron** [comment]
There are a few things I'd love clarification on to aid in the migration work:

1. There is a lack of documentation around error semantics for each method, such as:
  - impact on the current rangedloop cycle (current minimal implementation treats all errors as catastrophic events in the current cycle and causes a short circuit, which is different from segmentloop service semantics)
  - impact on future calls to the observer (e.g. if Process returns an error is Join still called, or Finish)
  - See [this comment](https://github.com/storj/storj/pull/5334#issuecomment-1339833944) for additional details.
2. Is there value in passing forking details to the Fork call, i.e., how many times fork will be called? 
For example, the gracefulexit pathcollector (i.e. segmentloop observer) has a configured batch size to (i think) prevent hammering the database. It's not yet clear if we should be dividing that batch size up amongst all of the forked partials or if each should just use the existing batch size (with a tradeoff between memory usage and database load). Currently the former strategy is not implementable because the observer does not know how many times fork is going to be called.
