### ISSUE TITLE
Satellite UI: Separate frontend and backend code

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#5494]
This is the first step necessary to enable continuous deployment of the satellite UI.
High level goal: Get rid of needing go templates for web/satellite/index.html
Suggested process:
* Add a generated type in `web/satellite/src/utils/config.gen.ts` (see private/apigen/tsgen.go for example of ts generation from go)
* Add a `gen.go` file to `satellite/console/consoleweb` which can be executed to generate the type
* pull data struct and config population outside of web server into its own function ([see here](https://github.com/storj/storj/blob/d76f764b72f223c8263e2e4c45d94f50241daf80/satellite/console/consoleweb/server.go#L433-L515))

e.g. a type is defined in `consoleweb`:
```
type ClientConfig struct { // used to be called `data`
    ExternalAddress                     string
    SatelliteName                         string
    SatelliteNodeURL                   string
    ...
}
```
is populated in some "setup" function:
```
func GetClientConfig(serverCfg consoleweb.Config) ClientConfig {
    return ClientConfig{
        ExternalAddress: serverCfg.path.to.ExternalAddress,
        SatelliteName: serverCfg.path.to.SatelliteName,
        ....
    }
}
```
which can be used with consoleweb/gen.go to generate web/satellite/src/utils/config.gen.ts, which looks something like:
```
export class SatelliteConfigStruct {
    public constructor(
        public externalAddress: string = '',
        public satelliteName: string = ''
        ...
    ) { }
}

export SatelliteConfig = new SatelliteConfigStruct(
    "http://localhost:10000",
    "storj",
    ...

```

Next steps:
* ensure typescript is properly generated for local and production defaults (as well as production overrides)
* remove "meta" configs and typescript utilities and use new config instead
* remove templating from index.html and consoleweb/server.go

Open questions:
* some values, e.g. ExternalAddress, are not known until runtime (they're not always directly based on the config). Not sure what to do about this

**Comment by egonelbre** [comment]
> `type ClientConfig struct {`

Name it something clearer, `Client` is very overloaded. e.g. `FrontendConfig`

> Add a gen.go file to satellite/console/consoleweb which can be executed to generate the type

I would actually recommend putting the code generator script into `web/satellite/src/utils/` and then it refers to the `storj.io/storj/console/consoleweb.FrontendConfig` package.

I also started wondering whether it makes sense to separate purely UI configuration from other config values, e.g. gateway address. Currently we are passing the config values through Go, because Go acts as the server, but it might not be that way forever. Even, if we never completely split them -- it might be useful to separate for clarity.

> func GetClientConfig(serverCfg consoleweb.Config) ClientConfig {

I'm not quite sure why this is necessary? Surely, the satellite would always need to provide the config -- so a default value for a wrong environment would be confusing.

> remove "meta" configs and typescript utilities and use new config instead

I recommend thinking through how to pass these configurable settings to the Vue as well. One helpful feature for development can be ability to change these values at runtime.

> `export class SatelliteConfigStruct {`

Keep the name consistent with the Go type.

**Comment by egonelbre** [comment]
One thing here, wouldn't using a separate FrontendConfig (Store) rather than keeping it in global AppStore make more sense?

**Comment by mobyvb** [comment]
> One thing here, wouldn't using a separate FrontendConfig (Store) rather than keeping it in global AppStore make more sense?

@egonelbre tracked in this ticket: https://github.com/storj/storj/issues/5797
