### ISSUE TITLE
Fix TestUnknownErrorDataRepair flakiness

### ISSUE THREAD

**Issue by VitaliiShpital** [storj/storj#5609]
https://build.dev.storj.io/blue/organizations/jenkins/storj-gerrit-verify/detail/storj-gerrit-verify/4399/tests/

**Comment by thepaul** [comment]
This test failed for the same reason that the ECRepairer tests did (see https://github.com/storj/storj/issues/5593). We did something that changes how long it tends to take for connections to happen (probably the addition of the Noise protocol) and now it's more likely for all the successes to happen before any failures. When this happens, the repair stops trying to get any more pieces and considers the repair to be done. The test then fails because it was expecting the repair to observe one piece download error.

To fix this test (and others of the same pattern) might be more intrusive, however. We don't have a simple way to pass a nonzero number for the number of expected errors to the repairer. I think we might need to make "minFailures" be an attribute on ECRepairer instead of an argument to (*ECRepairer).Get().

I don't think there have been many other problems with this test recently though. So I'm going to put off making those changes until it looks like we are having more problems.

**Comment by egonelbre** [comment]
related https://github.com/storj/storj/issues/5718
