### ISSUE TITLE
Investigate complexity of implementing global Satellite UI search

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#6202]
potential options:
* [Algolia](https://www.algolia.com/doc/ui-libraries/autocomplete/introduction/what-is-autocomplete/)
* [Flexsearch](https://github.com/nextapps-de/flexsearch)

How much effort would it be to integrate something like this into the Satellite UI, to allow the user to easily search for any section? Should we try to implement it in the vuetify app?

AC:
* timeboxed investigation (2 days max) to determine the difficulty/complexity of using a global search in the vuetify app
* discuss with the team, and based on discussion, create additional implementation tickets if the team is in favor of implementing global UI search

**Comment by wilfred-asomanii** [comment]
The complexity of this task will depend on which library/service we choose to implement this. It may also depend on how extensive we want the search to be; e.g.: whether we want to search through users' projects as well. In general, it should be pretty easy to do this, particularly if we chose to use either Flexsearch or fuse.js.
In this investigation, one service, Algolia, and two libraries (flexsearch, fuse.js) were tried. The demo changes are linked in the last two comments before this one. Performance wasn't considered in this investigation,
since the data we may want to search through is small, but it may be worth considering in the future.

* [Flexsearch](https://github.com/nextapps-de/flexsearch)/[Fuse.js](https://www.fusejs.io/)
        * Easy to implement. Though Fuse is significantly easy to understand given it has a great documentation. It has better typescript support too (the latest version of Flexsearch ships with a wrong, misleading type declaration file).
        * No external service required
        * The data to be searched can be stored locally, so we have more dynamic control over the data. We can update the index whenever we want with a user's Projects or Buckets for example.
        * Small library size with no dependency
        * May however not be as good as Algolia in terms of search quality.
        * [This](https://nextapps-de.github.io/flexsearch/bench/) benchmark compares the performance of these two, Flexsearch appears to be significantly ahead.
        * Fuse.js uses fuzzy search, which makes it typo tolerant to some extent and can give the indexes of matched characters, which may be useful for highlighting the matched characters in the search results.
* [Algolia](https://www.algolia.com/doc/ui-libraries/autocomplete/introduction/what-is-autocomplete/)
        * [Not completely free](https://www.algolia.com/pricing/). The free tier has a limit of 10k search requests/mo and $0.50/1k search requests/mo after that.
        * Requires an external service. The data to be searched has to be uploaded to the service, so we do not have as much dynamic control over the data as we would with the other two.
        * Not as easy to implement or understand. The complexity of implementation caused the demo to be be abandoned for the sake of time.
        * Sizable library with dependence on [Preact](https://preactjs.com/).
        * It does have better search quality than the other two.
        * It has a lot of features that may be useful in the future, such as typo tolerance, highlighting matched characters, analytics, etc.
        * It is however an overkill for this task, and may not be worth the cost and overhead of another service to track and maintain.
