### ISSUE TITLE
Implement authorization for admin API

### ISSUE THREAD

**Issue by shaupt131** [storj/storj#6207]
### Background:
We have to implement the authorization logic according to the design document.  Testing will be incorporated into this ticket as well.

### Acceptance Criteria:

- Update configuration to accept the new parameters to define which groups are assigned to each role.
- Create a high-level abstraction to get the authorization of the request headers, so the endpoints can use it. 
- Create a middleware to check the authorization and respond with unauthorized when the user isn't authorized without passing the request down the handlers chain.
- Create a middleware to send a header with each response of an authorized request with the user's role, so the front-end can hide/show components, input fields, etc.

**Comment by ifraixedes** [comment]
I unblocked it because I have the implementation and it's good to merge once is reviewed and approved despite it is not integrated with the example endpoint generated by the API generator because of the API generator issue that I reported on #6467.

The commit for review is https://review.dev.storj.io/c/storj/storj/+/11662

**Comment by ifraixedes** [comment]
Deployed in release v1.93.1
