### ISSUE TITLE
Implement private uplink method for ListObjectVersions

### ISSUE THREAD

**Issue by iglesiasbrandon** [storj/storj#6222]
### Description
The purpose of this ticket is to implement the Private uplink method for ListObjectVersions

Here is a starting point! 
- https://github.com/storj/uplink/blob/v1.11.0/objects.go#L67

### Acceptance Criteria
- The private uplink method for list object versions is implemented

**Comment by egonelbre** [comment]
Most of this can be implemented:

1. `storj.io/uplink/private/version` functions and iterator
2. protobuf definitions
3. metainfo endpoint

I just realized, we also might want to consider whether to reuse the list objects protobuf rather than implementing a separate API. The data flowing through should be pretty much the same.

**Comment by mniewrzal** [comment]
If we want to implement complete solution (uplink + satellite) on the top of current design we have (`versions` as int4) I believe we need to split this work into 2-3 tickets with some better descriptions what we want to achieve.

**Comment by jtolio** [comment]
Since we don't support versions (yet), 95% of this work is just setting up the plumbing for a parallel codepath for the existing ListObjects behavior.

If we had two parallel call pipelines (uplink to RPC to Satellite) that both listed objects (and one was called listobjectversions), i'd call this ticket done. Then all we'd have to do to support listobjectversions once we choose a schema is change the behavior to return more than one object version (possibly flagged as a delete marker) with a version id and that's it.

One additional thing to plumb is that the listobjectversions call has two continuation tokens - starting object offset to skip and starting version offset to skip. so plumbing that through on the request side would be nice.

I agree with Egon that a lot of the definitions between the two calls can be shared

**Comment by jtolio** [comment]
What tickets do you have in mind @mniewrzal ?

**Comment by mniewrzal** [comment]
at least separate tickets for libuplink and satellite with some reasonable acceptance criteria. Before comments above it was pretty undefined what needs to be done. I'm also fine putting **AC** here if having separate tickets is just my thing :-)

**Comment by dlamarmorgan** [comment]
https://review.dev.storj.io/c/storj/common/+/11126

**Comment by shaupt131** [comment]
This ticket is blocked by https://github.com/storj/storj/issues/6383 and https://github.com/storj/storj/issues/6384

**Comment by dlamarmorgan** [comment]
https://review.dev.storj.io/c/storj/uplink/+/11314
