### ISSUE TITLE
Investigate "daily usage" query performance improvements

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#6415]
On the QA satellite, fetching from the `daily-usage` endpoint can take 45 seconds or more (in some cases, it may be multiple minutes) on projects with 100+ buckets.

### AC
* investigate whether there are further improvements we can make to the query used by "daily usage" endpoint for situations where the user has a large number of buckets
* also consider if there are ways to make the user experience in the satellite UI better, in case significant improvements are difficult for the DB query; for example, would there be a way to partially load information in the UI so that it feels more responsive if the normal daily usage endpoint takes a long time?
* leave your notes and/or suggestions in a comment on this issue so that they can be discussed

Representative Customer Issue:
- https://github.com/storj/customer-issues/issues/1255

**Comment by cam-a** [comment]
It's definitely the index selection causing the problem.
Forcing the index on the query results in split-second completion on EU1.
So the question we face is figuring out how to make sure EU1 uses the best index in this case.
Discussion in the slack thread above

**Comment by cam-a** [comment]
Ok, this is two separate problems. Reopening

**Comment by ferristocrat** [comment]
https://github.com/storj/customer-issues/issues/1255 -- the customer here with the issue of:

**Comment by cam-a** [comment]
It turns out the query itself is fine. The decreased performance I saw with increased timespan and more buckets only occurred on the QA satellite, which is less provisioned than our production databases.
I was able to get EU1 to use the correct index by forcing statistics collection on the bucket_storage_tallies table. 
Testing on EU1, even querying the project with the most buckets for a timespan of 1 year, the results were returned very quickly. There is an index on project and interval_start. This makes this query fairly efficient. 
Therefore, I would say investing time in increasing performance of this operation does not give us much value right now.
However, here are some ideas for the future in case we come back to this:
- limit the timespan that can be requested
- do not display the graphs by default. Display them on request. This may make the UX experience better even if the query takes a while.
- store the summed storage data in a new table. Storage data is housed in bucket_storage_tallies. This table is generally very granular, and we need to scan many rows to get data we need. If instead some background chore did the summation and stored this value in a single row for a single day, it would be faster to retrieve.
- every time the dashboard is loaded it sends the daily usage request even if the timerange hasn't changed since the last time. Cache the data. The data for days in the past will never change.
