### ISSUE TITLE
Spaces shouldn't be allowed in password

### ISSUE THREAD

**Issue by ferristocrat** [storj/storj#6630]
### Problem
- possible to set _ (space) as password (see video below)

https://github.com/storj/storj/assets/7063002/0ba83134-79fa-42ac-a45e-a2b6505c7754

**Comment by onionjake** [comment]
Should the title be _only_ spaces shouldn't be allow in password?

**Comment by egonelbre** [comment]
Is there a reason you shouldn't use spaces in passwords? It seems like a perfectly valid character.

**Comment by jtolio** [comment]
i could be convinced that the rule should be that we trim spaces on the outside of the passphrase, and then if the passphrase is empty we reject empty passphrases, but interior spaces in a passphrase seems super good actually. i'm inclined to think that spaces in general are fine

**Comment by onionjake** [comment]
> block common and previously breached passwords

We can block passwords of 6 consecutive spaces under OWASP if we consider it too common, but instead of us trying to write our own common and previously breached passwords library there are others out there to use and could drop in (probably documented and prioritized separately).

As long as we are enforcing the minimum password length and the spaces function correctly as a password, I agree, this is not a bug and shouldn't be fixed.

**Comment by egonelbre** [comment]
If we have a password strength meter that should make it less of an issue.

**Comment by ferristocrat** [comment]
The goal of this was feature parity with what we have today. 

https://github.com/storj/storj/issues/6629 captures making passwords better.

**Comment by NiaStorj** [comment]
will close and work on #6629
