### ISSUE TITLE
Satellite UI: File browser upload changes

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#6853]
### AC:
* Change "drag and drop files to upload" to "drag and drop files or click here to upload"
  * when clicked, upload dialog is opened
* ~[IF POSSIBLE] - combine "upload file" and "upload folder" into the same action~
  * ~merge into a single "upload" button in the UI, where the user can select either files or folders to upload~
  * ~if this is not possible, respond in a comment to explain why, and disregard this AC~

**Comment by wilfred-asomanii** [comment]
It is not yet (possible/seamless) to combine folder and file selection in all browsers. The current way we select folders turns out to be the common way to allow the selection of both files and folders; `<input type="file" hidden multiple webkitdirectory mozdirectory >`.
However, this surprisingly only works to pick files and folders on Safari and not Mozilla and Chromium (Brave, Google Chrome). Another route is to use [showDirectoryPicker](https://developer.mozilla.org/en-US/docs/Web/API/Window/showDirectoryPicker), but browser support for this to little.

**Comment by wilfred-asomanii** [comment]
https://github.com/storj/storj/releases/tag/v1.102.3
