### ISSUE TITLE
Satellite UI: zkSync updates

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#6873]
UI changes:
- We need to address the banner that claims we don't support zkSync payments
- We need to make sure the "view" button on payment history tab routes to the correct block explorer.

### AC:
* correct link for zkSync transactions on token transactions list
* remove text in the UI that claims that we only support L1 transactions - TODO what should the new text be? Do we need to warn against sending certain types of L2 transactions?

**Comment by heunland** [comment]
Please specifically state in the warning message that we only accept ethereum based L1 or zksync Era STORJ deposits (unless we actually will also allow zkSync lite) and explicitly state that we do NOT accept STORJ deposits via other blockchains such as BNB, polygon etc since we did already have people try that.

**Comment by mobyvb** [comment]
@heunland @ferristocrat how does this look?
> Send only STORJ tokens via Layer 1 or zkSync Era transaction to this address.
Sending anything else other than STORJ token, or using any Layer 2 other than zkSync, such as BNB, Polygon, etc... will result in the loss of your deposit.

Please let us know if this looks good. If it does not look good, please provide exact text that you would like to use instead.

**Comment by wilfred-asomanii** [comment]
https://github.com/storj/storj/releases/tag/v1.101.2
