### ISSUE TITLE
Add the ability to select storage nodes in specific areas - Geo Fencing

### ISSUE THREAD

**Issue by iglesiasbrandon** [storj/storj#694]
----
👋 Hey! This is an issue that Storj would love the community's help on. If you have any questions about how to get started or want to discuss further, add a comment. Likewise, if you want to jump in, say so below. PRs accepted! 😄
----

When I am uploading a file to the network I want the ability to select a set of nodes within a specific radius of a point (Latitude/ Longitude). A Lat/long and radius would have to be included in the request the uplink makes to the satellite when asking for nodes.

**Comment by BlackDuck888** [comment]
For me a specific radius makes no sense. 

1. The geo data of IPs are inaccurate, all unknown or forced hidden will be located in the exact middle of a country from typical geo provider. 
2. A short geo distance is not the same to the technical distance. Routing, Hops, other latency problems.
3. The mean problem is to keep data in a specific country, and this will not necessary depends distance. If a uplink is located near a countryboarder the distance can be more near to nodes behind the boarder then an same country.

What i will need is to set/ keep the data within my or any specified land.

**Comment by subwolf** [comment]
Should be no problem to assign some specific areas a la dvd or bluray location settings, do a quick geoip lookup then assign an area based on that, nodes can exchange areas to find those closer. Nodes should never be more than 100ms apart, one would hope?

**Comment by sashahilton00** [comment]
given that IP geolocation is notoriously vague/inaccurate, might a possible halfway house be to allow a satellite to create a number of regions, since it is the orchestrator of data storage, and potentially categorise regions from IP address ranges and/or the IP ranges controlled by ASNs within a given area? At any rate, using peering information to categorise IP blocks into rough regions would be more inline with the general topology of the internet in comparison to overlaying geolocation data onto IP addresses.

**Comment by LaPetiteSouris** [comment]
**Proposition of implementation**

### Modification to add `node_region` information
1. In `satellite.overlay.service`, we need to add in to `NodeInfo` a field to indicate `region` when node checking in

```golang
// NodeCheckInInfo contains all the info that will be updated when a node checkins.
type NodeCheckInInfo struct {
	NodeID     storj.NodeID
	Address    *pb.NodeAddress
        Region      string
	LastNet    string
	LastIPPort string
	IsUp       bool
	Operator   *pb.NodeOperator
	Capacity   *pb.NodeCapacity
	Version    *pb.NodeVersion
}
```

2. Every time a node check in , in `satellite.satellitedb.overlaycache.UpdateCheckIn`, the extra piece of information `region` shall be added.
3.  A new column  in table `nodes` shall be added. E.g : `region`

### Identify Region from IP Addresses

I think that instead of using detailed geographical locations, it makes sense to use a high-level regions to cluster nodes into related regions based on geographical location.

Granted that nodes may be behind firewall, proxy, VPN...etc and my tries to hide its location completely, but it still makes sense to group nodes by general regions like: `eu-west`, `asia-pacific`...etc or something similar.

- if the IP address of the node is not hidden, the grouping nodes in rough `regions` would deliver the same result as cloud provider regions, like AWS `us-west-2` or something similar
- if IP address of the node is hidden, then the clustering information by regions is not correct, but this is exactly the same behavior we have at this moment: no differentiation in giving nodes based on `region` category.

In short, if the information of node IP is correct, it will be much better, but even if it is not correct, it will not be worst than now.

In order to do so, we could:

1. For each IP address, check the range to see to which `region` (may be countries as well) it belongs to.
2. We need an extra table in metadata database  :  

```SQL
CREATE DATABASE ip2location WITH ENCODING 'UTF8';
\c ip2location
CREATE TABLE ip2location_db3(
	ip_from bigint NOT NULL,
	ip_to bigint NOT NULL,
	country_code character(2) NOT NULL,
	country_name character varying(64) NOT NULL,
	region_name character varying(128) NOT NULL,
	city_name character varying(128) NOT NULL,
	CONSTRAINT ip2location_db1_pkey PRIMARY KEY (ip_from, ip_to)
);
```
_This table needs to be populated by some data from the web to indicate the IPv4 and IPv6 ranges by countries. Given that this kind of information is not going to change every day or every week (may be not even every month), it can be acceptable to have "stale data" in this table._

A good dataset is at [IP2Location](https://lite.ip2location.com/database/db3-ip-country-region-city)

Real question to discuss here:

- [ ] How do we initiate this new table for a new metadata database ?
- [ ] How do we keep this table in sync at a frequency like monthly or quarterly ?


What do you think ?

**Comment by stefanbenten** [comment]
Hello and thank you for the proposal @LaPetiteSouris !

Overall the idea here is a great starting point however it will/might have some problems that you partially already mentioned/covered. To mention some that come to mind:

- We should not let the nodes send in their region, as this is very error prone and hard to prove. I would rather base this on the actual check in IP(s) and determine the region on the satellite side.
Additionally I do not think we should store the IP-Region mapping in the database itself, rather than use the already existing lookup tools like IP2Locations or Maxminds GeoIP database (which we already use for the linksharing map).
- We would need to possible have a preference of region assignment based on IP protocol, since the geolocation assignment might differ between IPv4 (relatively precise) and IPv6 (very general and normally pointing to ISP head quarter only). This likely is just a flaw or problem of the rather improper implementation of IPv6 at this current stage, but might have an affect
- Should this approach that's proposed here be good enough to achieve compliance?
- how would the customer specify the geofencing? opt-in or opt-out for regions?
- not directly related, but we also need to think about our promises of having 99,x% availability for the file, which drastically is affected if one fences the data to a small set (say Europe-West-1, Europe-West-2 and Europe-West-3)


In terms of adding tables/columns to
the databases/tables, this is fairly easy and we have corresponding migration code that handles this if needed.
For keeping the data up2date I would as said above rely on services that do this as their main product like maxmind.

Looking forward to work on this more!

**Comment by LaPetiteSouris** [comment]
Hi. 

Thanks for the detailed feedback. Feel great to have the conversation going. Indeed, I only scratch the top of the iceberg.

> * We should not let the nodes send in their region, as this is very error prone and hard to prove. I would rather base this on the actual check in IP(s) and determine the region on the satellite side.
>   Additionally I do not think we should store the IP-Region mapping in the database itself, rather than use the already existing lookup tools like IP2Locations or Maxminds GeoIP database (which we already use for the linksharing map).

Agreed. The idea is not to let the node check in the region by itself. I was not very clear, but the idea would be to regenerate `region` from ip address upon each check in. `region` is auto-generated field.

I was thinking about using IP2Locations or Maxminds GeoIP in the beginning, but I am still not sure because request to integrate a new service into satellite would be hard to justify. But since you said somehow it is already there, it looks great because we non longer have to justify the integration.

And using those service relieves the huge pressure to keep IP-to-region data in-sync. However, I am thinking :
- What would be the work load impact on the IP2Locations or Maxmind GeoIP ? Since satellite would checkin nodes each and every x minutes, this could introduce I/O overhead ?
- Is it required to have a paid/premium plan to use external services like IP2Locations/Maxmind GeoIP if we hit their API constantly ?

Technically, having our own table in Metadata database would still require I/O, but since it's internal database, we do not have to make any justification on that point.

> * We would need to possible have a preference of region assignment based on IP protocol, since the geolocation assignment might differ between IPv4 (relatively precise) and IPv6 (very general and normally pointing to ISP head quarter only). This likely is just a flaw or problem of the rather improper implementation of IPv6 at this current stage, but might have an affect.

I would propose to have `regions` similar to other cloud provider. E.g: not city or even state precise, but rather generic like : `eu-west` or `eu-east` or `asia-pacific` ....etc .

Reasons:
- It is a good-enough solution, IMHO. As even cloud provider would do the same.
- Less headache for maintaining
- Simple enough to implement and maintain.
- Ipv4 or Ipv6 alike, we can achieve the same conformity if we just use generic regions.

Of course, if needed, further complex solutions can be envisaged, but I guess we can start simple.

> * Should this approach that's proposed here be good enough to achieve compliance?

Could you elaborate ? Compliance mean data governance compliance ?


> * how would the customer specify the geofencing? opt-in or opt-out for regions?
> * not directly related, but we also need to think about our promises of having 99,x% availability for the file, which drastically is affected if one fences the data to a small set (say Europe-West-1, Europe-West-2 and Europe-West-3)
> 

These 2 points are related:
- Storing/Retrieving data in specific regions will enhance speed, for sure, but it comes with a trade-off, which is the drop in availability of data. I cannot see any other way around.
- Given, that, the `geofencing` shall be opt-in, IMHO. The decision to go with that trade-off shall be in the hand of users and shall be decided based solely on their own business cases. In some case, it is not that bad actually to have data unavailable time to time but it would mean a lot to increase the data retrieval speed. On the other hand, some business use case would requires strictly availability up to 99,x% and they simply don't care if the data comes with a few seconds or even minutes of latency.

> In terms of adding tables/columns to
> the databases/tables, this is fairly easy and we have corresponding migration code that handles this if needed.

Amazing !
> For keeping the data up2date I would as said above rely on services that do this as their main product like maxmind.
> 

Agreed, with a few remarks above.
> Looking forward to work on this more!

It is amazing to get the discussion started !

**Comment by sashahilton00** [comment]
> Agreed. The idea is not to let the node check in the region by itself. I was not very clear, but the idea would be to regenerate `region` from ip address upon each check in. `region` is auto-generated field.

I wonder if it might not be possible/advisable to allow the node to check itself into a region if it opts to. The rationale behind this is as follows:

- IP geo-location databases are not necessarily accurate.
- Node operators are better positioned to provide accurate information on where their nodes are operating
- Given that this is a commercial data storage product, certain companies (such as ones in the EU) may need assurances that data remains within certain regions.
- Dynamic IP addresses and CG-NAT are becoming ever more prevalent, which can result in certain cases whereby the IP address does not accurately reflect the location of a server. Whilst I'm not sure how prevalent this issue is, I have recently used a (European) broadband connection where the ISP was routing packets back to the subscriber billing origin country, (ie. people paying with German debit cards were having data routed via their German gateway).

Leaving regulatory issues such as GDPR aside, generally the choice of region comes down to the expected latency between existing servers and the given region. Thus I propose that a two pronged approach be taken:

1.  A node operator can opt not to specify their region, in which case a combination of IP and ping checks to servers known to be hosted in certain regions take place (similar to [https://www.cloudping.info/](https://www.cloudping.info/), and the server is assigned to the region that it is most likely in.

2. A node operator opts to specify the region. The node requests a challenge seed from the satellite, which is to be completed by the ping server. The client connects to the ping server in a given region, at which point the challenge is completed, the ping server notes the request latency, and provides a signed response containing the IP, timestamp, node and latency details for the exchange. The client then sends the challenge seed and signed response along with it's region registration request, which is then validated by the satellite to be within an acceptable latency range, possibly derived from data gathered from other node latency tests in the region. Periodically the satellite may require the node to repeat the challenge.

The second approach has its pros and cons: there is additional overhead, as well as the need to operate a ping server in each region. The advantages are as follows: latency is hard to forge - the solution to lower latency is to be located closer to the ping server, ie. in the region. For nodes which have IPs that change fairly rapidly, one is not reliant on Maxmind database updates. Furthermore, if an operator knows that their server lies within a region, forcing the node to operate in that region within the constraints of the acceptable latency ranges should result in a faster network overall.

In the event that a node is mis-configured or malicious, this should be handled by the ping challenges; if a server is failing latency checks, and Maxmind GeoIP believes an IP to be in a different region, we can assume that he server is either mis-configured or lying. In this scenario, the node can be configured to do one of two things: a) accept the satellite's reassignment to a different region, at which point the server changes region. b) refuse to operate outside the specified region, in which case data is moved to a new node and the node is ejected from the network.

Depending on where Storj wants to go with regions, it then also becomes possible to start providing assurances about to the region that data is stored in, for example: `eu-west1` could contain nodes operating within Western Europe (eg. auto assigned to region, may have changed region in last 3 months, latency of <200ms, etc.), whilst `eu-west1-ha` contains a subset of those nodes with more desirable attributes (eg. node has locked itself to `eu-west1` and disabled auto-region assignment, has a consistent <120ms latency, not changed region in 6 months, >99.9% uptime, etc.) which is charged at a premium, in much the same way that the likes of AWS charges for different regions currently.

**Comment by LaPetiteSouris** [comment]
To resume, I think we face the dilemma:

- Either let the node check in or try to figure out the region of the node by the satellite, there is not guarantee that the information is correct.
- In return, if the feature intends to provide a strict guarantee about the location of nodes to store data (in term of data governance), then it would be extremely hard. 
- Finally, inline with the philosophy of distributed network, I do not think that we can provide such a strong guarantee to keep data in a specific regions.

If the feature is to provide _"data distribution in the best effort but without guarantee"_, then I think it simplifies the process. In such sense, let the node check in the location may make sense ( in the first version).

Any thoughts ?

**Comment by elek** [comment]
Please see #4227 for a proposed implementation.

There are two parts there:
 1. Improve the existing implementation to support placement constraints
 2. Implement geofencing with the help of an IP database
 
 The limitation of (2) is already discussed here. But I hope that with having the basic framework implemented we can continuously improve it and create better and better placement constraints.

**Comment by elek** [comment]
The first version of geofencing is implemented, I am closing this issue. Still it can be improved in the future (for example with adding API to self-define regions), but further improvements can be tracked in separated issues as this one was opened to discuss how is it possible to support geofencing.
