### ISSUE TITLE
Update process for self-serve account delete flow

### ISSUE THREAD

**Issue by NiaStorj** [storj/storj#7069]
Relevant discussion:  https://storj.slack.com/archives/C3T10U9AP/p1721167218281429
Relevant ticket with designs:  https://github.com/storj/storj/issues/7050

Our current implementation of self-serve delete does several steps _after_ the user flags themselves for deletion. We want to move these steps before. In other words, there are steps we want to require the user to do before they are allowed to flag themselves for deletion.

In particular, a customer should not be able to flag their account for deletion if:
* they have any buckets or objects
* they have unpaid invoices
* they have usage that has not yet been billed on an invoice

If one of these conditions is true, and the user attempts self-serve deletion, they should receive a message informing them about what they need to do (in some cases, what they need to do is just wait until invoicing occurs).

By moving these validation steps before self-serve deletion, we eliminate a lot of complexity, such as how to deal with charging a user after they have flaged themselves for deletion, but before we actually delete their account.

If the user has an outstanding Stripe balance, provide a link to request delete through support for a refund. Automating STORJ token refunds is out of scope for this change

### AC:
* validate that user has no unpaid invoices, no unbilled usage, and not buckets/objects before allowing them to trigger account deletion

**Comment by boshevski** [comment]
Design for step 1 of account delete - check if there are still buckets and inform the user to delete.
<img width="512" alt="delete-step1-buckets" src="https://github.com/user-attachments/assets/3e86e6f5-0dd3-48de-a4d4-a997972c2355">
If there are no buckets, skip this step and proceed with billing check.

**Comment by boshevski** [comment]
Design for step 2 of account delete - check if there are unpaid invoices and inform the user to pay.

<img width="473" alt="349197125-b9618589-8081-4a01-8d59-7cb0855b7df0" src="https://github.com/user-attachments/assets/e9a1bcfd-3409-444c-a205-9ba636849ee0">

**Comment by NiaStorj** [comment]
@cam-a this needs effort points

**Comment by cam-a** [comment]
@boshevski can we get designs for these parts of the ticket
`they have usage that has not yet been billed on an invoice [...] what they need to do is just wait until invoicing occurs`
and 
`If the user has an outstanding Stripe balance, provide a link to request delete through support for a refund`

**Comment by boshevski** [comment]
Hey @cam-a here is a design that works for both of these parts:

<img width="518" alt="delete-account-unpaid-usage" src="https://github.com/user-attachments/assets/4650c8eb-dc16-4c51-84f7-9804849f5d68">

We show the alert for balance only in cases of outstanding balance. Here is the dialog content:

There's some recent usage on your account that hasn't been paid yet. To delete your account, please follow these steps:

1. Please wait until the end of the current billing cycle (typically the end of the month)

2. We'll generate your final invoice then.

3. Once the invoice is paid, you can resume the account deletion process.

This typically occurs at the end of the month. We appreciate your patience.

If you have an outstanding balance or need immediate assistance, please contact our support team to request account deletion and discuss any potential refunds.

**Comment by heunland** [comment]
> Hey @cam-a here is a design that works for both of these parts:
> 
> <img alt="delete-account-unpaid-usage" width="518" src="https://private-user-images.githubusercontent.com/3217669/355089605-4650c8eb-dc16-4c51-84f7-9804849f5d68.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4Mjc1MjUsIm5iZiI6MTcyMzgyNzIyNSwicGF0aCI6Ii8zMjE3NjY5LzM1NTA4OTYwNS00NjUwYzhlYi1kYzE2LTRjNTEtODRmNy05ODA0ODQ5ZjVkNjgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTZUMTY1MzQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTFkOTUzNWQ3Mzk0ZTM1NGUwZjE4YzcyMDE4MDYwN2VlNDRjNmYyYjUzMmMwZGEzNTU1Yjg5M2Y5OGJhNmU2YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ._1JySI2OwECE1_L-3znx2HlV5E_HOy0MEYrM-YmTtYM">
> We show the alert for balance only in cases of outstanding balance. Here is the dialog content:
> 
> There's some recent usage on your account that hasn't been paid yet. To delete your account, please follow these steps:
> 
> 1. Please wait until the end of the current billing cycle (typically the end of the month)
> 2. We'll generate your final invoice then.
> 3. Once the invoice is paid, you can resume the account deletion process.
> 
> This typically occurs at the end of the month. We appreciate your patience.
> 
> If you have an outstanding balance or need immediate assistance, please contact our support team to request account deletion and discuss any potential refunds.

- the invoicing actually does not happen until the first week of the following months, so to avoid confusion and support tickets, instead of `This typically occurs at the end of the month.` we should say something like `This typically occurs at the beginning of the month following the month that usage is being invoiced for.`
- the phrase `If you have an outstanding balance` seems confusing, I think you meant to say `If you have any remaining balance from STORJ deposits in your account` 
- we do not want them to file support tickets for manual account deletion if they discover they have usage during the current month which would potentially mean a balance outstanding to be paid by them at next invoicing, but follow the workflow as shown in the screenshots above. Only if they still have a STORJ balance in their account even after their last invoice has been paid should they ask us for a refund via support ticket. 
I think they could still use the same workflow as described in this github issue to achieve the account deletion. I am only worried about if we can still query what is the remaining balance owed to them in storjscan after their account has already been deleted. I have noticed that this info may become unavailable via the queries we usually use to determine how much balance someone has from STORJ deposits. Example: https://redash.storj.tools/queries/3717?p_email=vincenzo.oliviero%40sat-online.it

**Comment by boshevski** [comment]
Thanks for the feedback @heunland
