### ISSUE TITLE
storj/pkg/satellite/users.go import uuid is not standardized

### ISSUE THREAD

**Issue by Fatfish90** [storj/storj#942]
Hi recently I read the storj golang code.
Why  storj/pkg/satellite/users.go import "github.com/skyrings/skyring-common/tools/uuid"
"github.com/satori/go.uuid" is more popular.

**Comment by egonelbre** [comment]
Hi, thanks for pointing it out.

At the moment we used `github.com/skyrings/skyring-common/tools/uuid` because we already had it in our dependency graph indirectly due to `github.com\minio\minio`.

We will eventually move to using `github.com/gofrs/uuid` which is the maintained fork of `github.com/satori/go.uuid`. However, that package is still a little in flux, so didn't want to do the switch yet.

**Comment by egonelbre** [comment]
We decided to move to https://github.com/storj/common/blob/master/uuid/uuid.go and have removed these external dependencies.
